export type { MeyaIcon, MeyaIconProps } from 'meya-icons/react/outline';

export {
    UserActivity as Activity,
    AlertCircle,
    AlertCircle as AlertCircleIcon,
    AlertCircle as CircleAlert,
    AlertTriangle as TriangleAlert,
    ArrowDown,
    ArrowDown as ChevronDown,
    ArrowDown as ChevronDownIcon,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowUp as ChevronUpIcon,
    Assignment as BookOpenCheck,
    Book as BookOpen,
    Save as Bookmark,
    Bug,
    Camera as ScanLine,
    Chat as MessageCircle,
    Check,
    Check as CheckIcon,
    CheckCircle,
    CheckCircle as BadgeCheck,
    CheckCircle as BookmarkCheck,
    CheckCircle as CheckCircle2,
    CheckCircle as MailCheck,
    ChevronRight,
    ChevronRight as ChevronRightIcon,
    ChevronsDown as ChevronsUpDown,
    Circle,
    Circle as CircleIcon,
    Clock as Clock3,
    Compass,
    Copy,
    Dashboard as LayoutDashboard,
    Document as CaseSensitive,
    Document as FileText,
    Quiz as FileQuestion,
    Edit,
    Edit as PenLine,
    Edit as Pencil,
    Email,
    Exam,
    Exam as ClipboardCheck,
    Exam as ClipboardList,
    ExpandDiagonal,
    Feedback,
    Unlock as Eye,
    Lock as EyeOff,
    File,
    Folder,
    Folder as FolderGit2,
    Grid as LayoutGrid,
    Headphones,
    HelpCircle,
    HelpCircle as CircleHelp,
    InfoCircle,
    Key as KeyRound,
    Layers as Layers3,
    Library as LibraryBig,
    List,
    ListBulleted as Tags,
    Lock,
    Lock as LockKeyhole,
    Logout as LogOut,
    Menu,
    Message,
    MessageQuestion,
    Message as MessageSquarePlus,
    Message as MessageSquareText,
    MessageAlert as MessageSquareWarning,
    MessageQuestion as Bot,
    Microphone as Mic,
    Minus,
    More,
    More as MoreHorizontal,
    WorldTime as Languages,
    Outbox as Send,
    Play,
    Play as CirclePlay,
    Plus,
    Refresh,
    Refresh as Loader2Icon,
    Refresh as LoaderCircle,
    Refresh as RefreshCw,
    RotateLeft as RotateCcw,
    RotateLeft,
    Save,
    Search,
    Settings,
    Shield as ShieldCheck,
    Sidebar as PanelLeftCloseIcon,
    Sidebar as PanelLeftOpenIcon,
    SlidersHorizontal as ListFilter,
    SlidersHorizontal as Settings2,
    Square,
    Star,
    Statistics as ChartNoAxesCombined,
    Calendar,
    Flag,
    Gauge,
    Trash,
    Trash as Trash2,
    User,
    User as UserRound,
    UserBlocked as UserRoundX,
    UserVerified as UserRoundCheck,
    Users,
    Upload,
    GraduationCap,
    Volume,
    Volume as AudioLines,
    Volume as Volume2,
    Layers as Workflow,
    X,
    X as XIcon,
} from 'meya-icons/react/outline';
