import { usePage } from "@inertiajs/react";

export type UiLocale = "id" | "su";

const su: Record<string, string> = {
    "Beranda / Dasbor": "Tepas / Dasbor",
    "Bahasa Sunda": "Basa Sunda",
    "KELAS BELAJAR": "KELAS DIAJAR",
    "AKUN SAWALA": "AKUN SAWALA",
    "Sawala": "Sawala",
    "Aksara Sunda": "Aksara Sunda",
    "Latihan & Aksara": "Latihan & Aksara",
    "Tutor AI": "Tutor AI",
    "Progres Belajar": "Kamajuan Diajar",
    Ringkasan: "Ringkesan",
    "Kelas & Pelajaran": "Kelas & Pangajaran",
    "Kosakata & Konteks": "Kekecapan & Kontéks",
    "Latihan & Soal": "Latihan & Patalékan",
    "Audio & Media": "Audio & Média",
    "Pelajar & Progres": "Murid & Kamajuan",
    "Bahasa & Aksara Sunda": "Basa & Aksara Sunda",
    "Navigasi admin": "Navigasi pangurus",
    "Navigasi belajar": "Navigasi diajar",
    "Bantuan belajar": "Pitulung diajar",
    "Bingung tentang tata bahasa atau aksara? Tanyakan kepada tutor.": "Teu acan ngartos tata basa atanapi aksara? Taroskeun ka tutor.",
    "Buka tutor": "Buka tutor",
    "Pengaturan akun": "Setélan akun",
    "Pengaturan & Bahasa": "Setélan & Basa",
    Keluar: "Kaluar",
    "Buka menu": "Buka ménu",
    "Buka menu admin": "Buka ménu pangurus",
    "Pilih halaman": "Pilih kaca",
    "Cari materi": "Téangan matéri",
    "Cari kosakata, aksara, atau pelajaran": "Téangan kekecapan, aksara, atanapi pangajaran",
    "pelajaran selesai": "pangajaran réngsé",
    latihan: "latihan",
    "Profil & pengaturan": "Profil & setélan",
    "Atur profil, bahasa tampilan, dan keamanan akun Anda.": "Atur profil, basa tampilan, sareng kaamanan akun anjeun.",
    Pengaturan: "Setélan",
    Beranda: "Tepas",
    Profil: "Profil",
    Keamanan: "Kaamanan",
    "Bahasa tampilan": "Basa tampilan",
    "Pilih bahasa untuk menu dan petunjuk aplikasi. Materi pelajaran tetap menggunakan bahasa aslinya.": "Pilih basa pikeun ménu sareng pituduh aplikasi. Eusi pangajaran tetep nganggo basa aslina.",
    "Bahasa Indonesia": "Basa Indonésia",
    "Bahasa berhasil diubah.": "Basa parantos dirobih.",
    "Pengaturan profil": "Setélan profil",
    "Keamanan akun": "Kaamanan akun",
    "Ubah kata sandi": "Robih kecap akses",
    "Gunakan kata sandi yang kuat dan tidak digunakan di tempat lain": "Anggo kecap akses anu kuat sareng teu dianggo di tempat sanés",
    "Kata sandi saat ini": "Kecap akses ayeuna",
    "Kata sandi baru": "Kecap akses énggal",
    "Ulangi kata sandi baru": "Balikan kecap akses énggal",
    "Simpan kata sandi": "Simpen kecap akses",
    "Kata sandi": "Kecap akses",
    "Hapus akun": "Pupus akun",
    "Hapus akun dan seluruh data yang terkait.": "Pupus akun sareng sadaya data nu patali.",
    "Perhatian": "Perhatosan",
    "Tindakan ini permanen dan tidak dapat dibatalkan.": "Léngkah ieu permanén sareng teu tiasa dibolaykeun.",
    "Yakin ingin menghapus akun?": "Yakin badé mupus akun?",
    "Setelah akun dihapus, seluruh data terkait juga akan dihapus permanen. Masukkan kata sandi untuk mengonfirmasi tindakan ini.": "Sanggeus akun dipupus, sadaya data nu patali ogé bakal dipupus permanén. Lebetkeun kecap akses kanggo mastikeun léngkah ieu.",
    "Autentikasi dua faktor": "Auténtikasi dua faktor",
    "Atur lapisan keamanan tambahan untuk akun Anda.": "Atur lapisan kaamanan tambahan kanggo akun anjeun.",
    "Saat masuk, masukkan kode sekali pakai dari aplikasi autentikasi di ponsel Anda.": "Nalika lebet, lebetkeun kode sakali anggo tina aplikasi auténtikasi dina telepon anjeun.",
    "Matikan autentikasi dua faktor": "Pareuman auténtikasi dua faktor",
    "Kode sekali pakai dari aplikasi autentikasi akan diminta setiap kali Anda masuk.": "Kode sakali anggo tina aplikasi auténtikasi bakal dipénta saban anjeun lebet.",
    "Lanjutkan pengaturan": "Teraskeun pangaturan",
    "Aktifkan autentikasi dua faktor": "Hurungkeun auténtikasi dua faktor",
    "Autentikasi dua faktor aktif": "Auténtikasi dua faktor hurung",
    "Autentikasi dua faktor aktif. Pindai kode QR atau masukkan kunci pengaturan ke aplikasi autentikasi Anda.": "Auténtikasi dua faktor hurung. Pindai kode QR atanapi lebetkeun konci pangaturan kana aplikasi auténtikasi anjeun.",
    "Verifikasi kode autentikasi": "Vérifikasi kode auténtikasi",
    "Masukkan kode 6 digit dari aplikasi autentikasi Anda.": "Lebetkeun kode 6 digit tina aplikasi auténtikasi anjeun.",
    "Pindai kode QR atau masukkan kunci pengaturan ke aplikasi autentikasi untuk menyelesaikan pengaktifan.": "Pindai kode QR atanapi lebetkeun konci pangaturan kana aplikasi auténtikasi kanggo ngaréngsékeun panghurungan.",
    "Tutup": "Tutup",
    "atau masukkan kodenya secara manual": "atanapi lebetkeun kodena sacara manual",
    "Kembali": "Balik",
    "Konfirmasi": "Pastikeun",
    "Kode pemulihan autentikasi dua faktor": "Kode pamulihan auténtikasi dua faktor",
    "Kode ini membantu memulihkan akses jika perangkat autentikasi hilang. Simpan di pengelola kata sandi yang aman.": "Kode ieu ngabantosan mulihkeun aksés upami alat auténtikasi leungit. Simpen dina pangatur kecap akses anu aman.",
    "kode pemulihan": "kode pamulihan",
    "Kode pemulihan": "Kode pamulihan",
    "Memuat kode pemulihan": "Nuju ngamuat kode pamulihan",
    "Buat kode baru": "Jieun kode énggal",
    "Setiap kode hanya dapat digunakan sekali dan akan terhapus setelah digunakan. Untuk membuat kode baru, pilih": "Saban kode ngan tiasa dianggo sakali sareng bakal dipupus sanggeus dianggo. Kanggo nyieun kode énggal, pilih",
    "di atas.": "di luhur.",
    "Sembunyikan": "Sumputkeun",
    "Lihat": "Tingali",
    "Passkey": "Konci aksés",
    "Kelola passkey untuk masuk tanpa kata sandi.": "Atur konci aksés kanggo lebet tanpa kecap akses.",
    "Belum ada passkey": "Teu acan aya konci aksés",
    "Tambahkan passkey agar dapat masuk tanpa kata sandi.": "Tambihkeun konci aksés supados tiasa lebet tanpa kecap akses.",
    "Browser ini belum mendukung passkey.": "Panyungsi ieu teu acan ngadukung konci aksés.",
    "Tambahkan passkey": "Tambihkeun konci aksés",
    "Nama passkey": "Nami konci aksés",
    "Nama ini membantu Anda mengenali passkey nanti.": "Nami ieu ngabantosan anjeun mikawanoh konci aksés engké.",
    "Contoh: laptop atau ponsel saya": "Conto: laptop atanapi telepon abdi",
    "Mendaftarkan...": "Nuju ngadaptarkeun...",
    "Daftarkan passkey": "Daptarkeun konci aksés",
    "Ditambahkan": "Ditambihkeun",
    "Terakhir digunakan": "Panungtung dianggo",
    "Hapus passkey": "Pupus konci aksés",
    "Hapus passkey “": "Pupus konci aksés “",
    "”? Anda tidak dapat lagi menggunakannya untuk masuk.": "”? Anjeun moal tiasa nganggo deui kanggo lebet.",
    "PROFIL SAYA": "PROFIL ABDI",
    Pelajar: "Murid",
    "Perbarui nama dan alamat email Anda": "Robih nami sareng alamat email anjeun",
    Nama: "Nami",
    "Nama lengkap": "Nami lengkep",
    "Alamat email": "Alamat email",
    Simpan: "Simpen",
    "Alamat email Anda belum diverifikasi.": "Alamat email anjeun teu acan diverifikasi.",
    "Kirim ulang email verifikasi.": "Kirim deui email vérifikasi.",
    "Tautan verifikasi baru telah dikirim ke email Anda.": "Tumbu vérifikasi énggal parantos dikirim ka email anjeun.",
    "STUDIO ADMIN / PENGELOLAAN": "STUDIO PANGURUS / PANGATURAN",
    "SAWALA · STUDIO KONTEN": "SAWALA · STUDIO EUSI",
    "Kelola pengalaman belajar yang bermakna.": "Atur pangalaman diajar nu aya mangpaatna.",
    "Susun kelas, lengkapi materi, dan tinjau progres pelajar dari satu ruang kerja.": "Susun kelas, lengkepan matéri, tur tingali kamajuan murid dina hiji rohangan gawé.",
    "Kelola kelas belajar": "Atur kelas diajar",
    "Kelas belajar": "Kelas diajar",
    "terbuka untuk pelajar": "kabuka pikeun murid",
    "Pelajaran siap tayang": "Pangajaran siap dipedalkeun",
    "masih draf atau ditinjau": "masih draf atanapi ditinjau",
    "Pelajar terdaftar": "Murid kadaptar",
    "Aktivitas tersedia di laporan pelajar": "Kagiatan aya dina laporan murid",
    "Kelas yang dikelola": "Kelas nu diatur",
    "Pilih kelas untuk melanjutkan penyusunan materi.": "Pilih kelas pikeun nuluykeun nyusun matéri.",
    "Lihat semua": "Tingali sadayana",
    "Alur penerbitan": "Léngkah medalkeun",
    "Materi harus lengkap dan ditinjau sebelum dibuka untuk pelajar.": "Matéri kedah lengkep tur ditinjau sateuacan dibuka pikeun murid.",
    "Susun pelajaran": "Susun pangajaran",
    "Tambahkan isi materi, contoh, dan latihan.": "Tambihkeun eusi matéri, conto, sareng latihan.",
    "Tinjau konten": "Tinjau eusi",
    "Periksa ragam bahasa, aksara, dan jawaban.": "Pariksa ragam basa, aksara, sareng jawaban.",
    "Terbitkan berurutan": "Pedalkeun sacara runtuy",
    "Pelajaran, unit, lalu kelas belajar.": "Pangajaran, unit, teras kelas diajar.",
    "Kelola kelas": "Atur kelas",
    "Pilih kelas yang dikelola": "Pilih kelas nu diatur",
    "kelas tersedia": "kelas sayogi",
    "Cari kelas": "Téangan kelas",
    "Filter status kelas": "Saring status kelas",
    "Semua status": "Sadayana status",
    "Tidak ada kelas yang cocok. Ubah kata kunci atau status.": "Teu aya kelas nu cocog. Robih kecap konci atanapi status.",
    "Buat kelas": "Jieun kelas",
    "Ubah kelas": "Robih kelas",
    "Unit pembelajaran": "Unit pangajaran",
    "Pilih unit untuk mengatur pelajaran di dalamnya.": "Pilih unit pikeun ngatur pangajaran di jerona.",
    "Tambah unit": "Tambah unit",
    "UNIT TERPILIH": "UNIT KAPILIH",
    "Ubah unit": "Robih unit",
    "Urutan pelajaran": "Runtuyan pangajaran",
    "Tambah pelajaran": "Tambah pangajaran",
    "Hapus filter": "Pupus saringan",
    "Entri kosakata & aksara": "Éntri kekecapan & aksara",
    "Entri berasal dari blok materi pada pelajaran.": "Éntri asalna tina blok matéri dina pangajaran.",
    "Buka kelas belajar": "Buka kelas diajar",
    "Latihan yang tersusun": "Latihan nu parantos disusun",
    "Kelola soal dan kunci jawaban pada latihan yang sudah dibuat.": "Atur patalékan sareng konci jawaban dina latihan nu parantos dijieun.",
    "Tambah soal": "Tambah patalékan",
    "Kelola pelajaran": "Atur pangajaran",
    "Audio pelafalan": "Audio lafal",
    "Berkas audio tersimpan pada blok materi terkait.": "Berkas audio disimpen dina blok matéri nu patali.",
    "Audio tidak tersedia.": "Audio teu sayogi.",
    "Kelola materi": "Atur matéri",
    "Aktivitas pelajar": "Kagiatan murid",
    "Jumlah pelajaran yang dituntaskan dan percobaan latihan dari data akun.": "Jumlah pangajaran nu diréngsékeun sareng usaha latihan tina data akun.",
    "Pelajaran selesai": "Pangajaran réngsé",
    "Percobaan latihan": "Usaha latihan",
    "Cari konten": "Téangan eusi",
    "EDITOR PELAJARAN": "ÉDITOR PANGAJARAN",
    "Ubah pelajaran": "Robih pangajaran",
    "Susun teks dan contoh sesuai urutan belajar.": "Susun téks sareng conto nurutkeun runtuyan diajar.",
    "Blok materi": "Blok matéri",
    "Konteks:": "Kontéks:",
    "Audio tersedia": "Audio sayogi",
    "Tambah materi": "Tambah matéri",
    "Soal dinilai menggunakan kunci jawaban admin.": "Patalékan dipeunteun nganggo konci jawaban pangurus.",
    "Tambah latihan": "Tambah latihan",
    "Batal": "Bolay",
    "Hapus": "Pupus",
    "Konten ini beserta semua bagian di dalamnya akan dihapus secara permanen.": "Eusi ieu sareng sadaya bagian di jerona bakal dipupus salamina.",
    "Menghapus...": "Nuju mupus...",
    "Ya, hapus": "Muhun, pupus",
    "Konten berhasil dihapus.": "Eusi parantos dipupus.",
    "Pilih opsi": "Pilih pilihan",
    "Menyimpan...": "Nuju nyimpen...",
    "Simpan perubahan": "Simpen parobahan",
    "Perubahan berhasil disimpan.": "Parobahan parantos disimpen.",
    "Draf": "Draf",
    "Ditinjau": "Ditinjau",
    "Terbit": "Medal",
    "Diarsipkan": "Diarsipkeun",
    "Penjelasan": "Panjelasan",
    "Kosakata": "Kekecapan",
    "Dialog": "Paguneman",
    "Pilihan ganda": "Pilihan ganda",
    "Mencocokkan": "Nyocogkeun",
    "Melengkapi teks": "Ngalengkepan téks",
    "Susun urutan": "Susun runtuyan",
    "Pilih aksara": "Pilih aksara",
    "Judul": "Judul",
    "Urutan tampil": "Runtuyan tampilan",
    "Angka yang lebih kecil tampil lebih dulu.": "Angka nu leuwih leutik dipidangkeun heula.",
    "Status konten": "Status eusi",
    "Jenis blok": "Jinis blok",
    "Judul blok": "Judul blok",
    "Isi materi": "Eusi matéri",
    "Tulisan Latin": "Tulisan Latin",
    "Aksara Sunda (Unicode)": "Aksara Sunda (Unicode)",
    "Arti Bahasa Indonesia": "Harti dina Basa Indonésia",
    "Ragam wilayah": "Ragam wewengkon",
    "Tingkat tutur": "Undak usuk basa",
    "Konteks pemakaian": "Kontéks pamakéan",
    "MP3, WAV, OGG, atau M4A. Maksimum 10 MB.": "MP3, WAV, OGG, atanapi M4A. Panggedéna 10 MB.",
    "Jenis soal": "Jinis patalékan",
    "Instruksi soal": "Pituduh patalékan",
    "Pilihan / bagian (satu per baris)": "Pilihan / bagian (hiji per padalisan)",
    "Jawaban benar": "Jawaban leres",
    "Penjelasan untuk pelajar": "Panjelasan kanggo murid",
    "Nama kelas": "Nami kelas",
    "Deskripsi singkat": "Pedaran singget",
    "Tujuan unit": "Tujuan unit",
    "Ringkasan pelajaran": "Ringkesan pangajaran",
    "Nama latihan": "Nami latihan",
    "Ringkasan pengelolaan": "Ringkesan pangaturan",
    "Kelas & pelajaran": "Kelas & pangajaran",
    "Kosakata & konteks": "Kekecapan & kontéks",
    "Latihan & soal": "Latihan & patalékan",
    "Audio & media": "Audio & média",
    "Pelajar & progres": "Murid & kamajuan",
    "Lihat apa yang perlu disiapkan sebelum pelajar mulai belajar.": "Tingali naon waé nu kedah disiapkeun sateuacan murid ngamimitian diajar.",
    "Susun unit, tulis materi, dan terbitkan pelajaran.": "Susun unit, tulis matéri, sareng pedalkeun pangajaran.",
    "Tinjau kosakata, aksara, dan ragam pemakaian dalam materi.": "Tinjau kekecapan, aksara, sareng ragam pamakéan dina matéri.",
    "Kelola latihan dan kunci jawaban untuk setiap pelajaran.": "Atur latihan sareng konci jawaban unggal pangajaran.",
    "Kelola audio pelafalan yang terhubung dengan materi.": "Atur audio lafal nu nyambung kana matéri.",
    "Lihat aktivitas belajar untuk mengevaluasi materi.": "Tingali kagiatan diajar pikeun meunteun matéri.",
    "Ubah kelas belajar": "Robih kelas diajar",
    "Buat kelas belajar": "Jieun kelas diajar",
    "Perbarui informasi dan status kelas belajar.": "Robih inpormasi sareng status kelas diajar.",
    "Kelas baru disimpan sebagai draf. Setelah itu, tambahkan unit dan pelajaran sebelum menerbitkannya.": "Kelas énggal disimpen salaku draf. Teras tambihkeun unit sareng pangajaran sateuacan dipedalkeun.",
    "Kelas berhasil diperbarui.": "Kelas parantos dirobih.",
    "Kelas baru berhasil dibuat.": "Kelas énggal parantos dijieun.",
    "Unit pada kelas": "Unit dina kelas",
    "Susun tujuan dan urutan belajar.": "Susun tujuan sareng runtuyan diajar.",
    "Pelajaran pada unit": "Pangajaran dina unit",
    "Soal untuk": "Patalékan kanggo",
    "Pelajar akan melihat penjelasan setelah mengirim jawaban.": "Murid bakal ningali panjelasan saatos ngirim jawaban.",
    "Ubah blok materi": "Robih blok matéri",
    "Tambah blok materi": "Tambah blok matéri",
    "Teks, kosakata, aksara, konteks pemakaian, dan audio dalam satu blok.": "Téks, kekecapan, aksara, kontéks pamakéan, sareng audio dina hiji blok.",
    "Ubah latihan": "Robih latihan",
    "Beri judul latihan sebelum menambahkan soal dan kunci jawaban.": "Pasihan judul latihan sateuacan nambihan patalékan sareng konci jawaban.",
    "Ubah soal": "Robih patalékan",
    "Belum ada kelas belajar": "Teu acan aya kelas diajar",
    "Buat kelas untuk mulai mengatur unit dan pelajaran.": "Jieun kelas kanggo ngamimitian ngatur unit sareng pangajaran.",
    "Pilih kelas belajar": "Pilih kelas diajar",
    "Cari kelas...": "Téangan kelas...",
    "Belum ada unit": "Teu acan aya unit",
    "Tambahkan unit untuk mulai menyusun urutan belajar.": "Tambihkeun unit kanggo ngamimitian nyusun runtuyan diajar.",
    "Belum ada pelajaran": "Teu acan aya pangajaran",
    "Buat pelajaran pertama untuk unit ini.": "Jieun pangajaran munggaran kanggo unit ieu.",
    "Kelas tidak ditemukan": "Kelas teu kapanggih",
    "Ubah pencarian atau filter status untuk melihat kelas lain.": "Robih pamilarian atanapi saringan status kanggo ningali kelas sanés.",
    "Buat kelas pertama Anda untuk memulai.": "Jieun kelas munggaran anjeun kanggo ngamimitian.",
    "Belum ada ringkasan pelajaran.": "Teu acan aya ringkesan pangajaran.",
    "Ubah entri": "Robih éntri",
    "Ubah blok audio": "Robih blok audio",
    "Hapus blok": "Pupus blok",
    "Hapus latihan": "Pupus latihan",
    "Hapus soal": "Pupus patalékan",
    "Cari kata, arti, aksara, atau ragam...": "Téangan kecap, harti, aksara, atanapi ragam...",
    "Tidak ada entri yang cocok": "Teu aya éntri nu cocog",
    "Belum ada kosakata atau aksara": "Teu acan aya kekecapan atanapi aksara",
    "Coba istilah pencarian lain.": "Coba istilah pamilarian sanés.",
    "Tambahkan blok kosakata atau aksara pada pelajaran untuk melihatnya di sini.": "Tambihkeun blok kekecapan atanapi aksara dina pangajaran kanggo ningalina di dieu.",
    "Cari judul latihan atau pelajaran...": "Téangan judul latihan atanapi pangajaran...",
    "Latihan tidak ditemukan": "Latihan teu kapanggih",
    "Belum ada latihan": "Teu acan aya latihan",
    "Coba kata pencarian lain.": "Coba kecap pamilarian sanés.",
    "Buka pelajaran dalam kelas belajar, lalu tambahkan latihan dan soal.": "Buka pangajaran dina kelas diajar, teras tambihkeun latihan sareng patalékan.",
    "Cari audio berdasarkan kata atau pelajaran...": "Téangan audio dumasar kecap atanapi pangajaran...",
    "Audio tidak ditemukan": "Audio teu kapanggih",
    "Belum ada audio": "Teu acan aya audio",
    "Coba pencarian lain.": "Coba pamilarian sanés.",
    "Unggah pelafalan pada blok materi agar dapat didengarkan pelajar.": "Unggah lafal kana blok matéri sangkan tiasa didangu ku murid.",
    "Cari nama atau email pelajar...": "Téangan nami atanapi email murid...",
    "Pelajar tidak ditemukan": "Murid teu kapanggih",
    "Belum ada pelajar": "Teu acan aya murid",
    "Coba nama atau email lain.": "Coba nami atanapi email sanés.",
    "Aktivitas akan terlihat setelah akun pelajar terdaftar dan mulai belajar.": "Kagiatan bakal katingali saatos akun murid kadaptar sareng ngamimitian diajar.",
    "Isi pelajaran": "Eusi pangajaran",
    "Materi belum diisi": "Matéri teu acan dieusi",
    "Pelajaran memerlukan paling sedikit satu blok materi sebelum bisa diterbitkan.": "Pangajaran peryogi sahenteuna hiji blok matéri sateuacan tiasa dipedalkeun.",
    "Tambahkan latihan, lalu tulis soal, jawaban, dan penjelasannya.": "Tambihkeun latihan, teras tulis patalékan, jawaban, sareng panjelasanana.",
    "RUANG BELAJAR": "ROHANGAN DIAJAR",
    "Dasbor belajar": "Dasbor diajar",
    "Sedikit demi sedikit, makin mahir berbahasa Sunda.": "Saeutik-saeutik, beuki mahér nyarios Basa Sunda.",
    "Mulai perjalanan belajarmu hari ini.": "Mimitian lalampahan diajar anjeun dinten ieu.",
    "Lanjutkan": "Teruskeun",
    "dan temukan hal baru di setiap pelajaran.": "sareng panggihan hal énggal dina unggal pangajaran.",
    "Pilih kelas Bahasa Sunda atau Aksara Sunda untuk membuka pelajaran pertama.": "Pilih kelas Basa Sunda atanapi Aksara Sunda kanggo muka pangajaran munggaran.",
    "Lanjutkan belajar": "Teruskeun diajar",
    "Lihat kelas belajar": "Tingali kelas diajar",
    "Belajar Bahasa dan Aksara Sunda": "Diajar Basa sareng Aksara Sunda",
    "Ruang saya": "Rohangan abdi",
    "Masuk": "Lebet",
    "Buka ruang kelola": "Buka rohangan pangaturan",
    "Lanjut belajar": "Teruskeun diajar",
    "Mulai belajar": "Mimitian diajar",
    "Navigasi utama": "Navigasi utama",
    "Buka menu navigasi": "Buka ménu navigasi",
    "Tutup menu navigasi": "Tutup ménu navigasi",
    "Cara belajar": "Cara diajar",
    "Daftar gratis": "Daptar gratis",
    "Mulai belajar gratis": "Mimitian diajar gratis",
    "Jelajahi cara belajar": "Jajah cara diajar",
    "Ruang belajar Bahasa dan Aksara Sunda": "Rohangan diajar Basa sareng Aksara Sunda",
    "Pilih fitur untuk melihat pratinjau": "Pilih fitur kanggo ningali sawangan",
    "Kelas Bahasa Sunda": "Kelas Basa Sunda",
    "Mulai dari sapaan, kosakata, sampai ragam tutur dalam konteksnya.": "Mimitian tina salam, kekecapan, dugi ka ragam basa sareng kontéksna.",
    "Pelajari karakter, rarangkén, membaca, dan menulis secara bertahap.": "Diajar karakter, rarangkén, maca, sareng nyerat sacara runtuy.",
    "Latihan setelah belajar": "Latihan saatos diajar",
    "Coba soal singkat dan lihat penjelasan untuk menguatkan pemahaman.": "Cobi patalékan pondok sareng tingali panjelasan kanggo nguatkeun pamahaman.",
    "Tanya Tutor AI": "Taroskeun ka Tutor AI",
    "Diskusikan materi dan lihat rujukan pelajaran yang digunakan.": "Sawalakeun matéri sareng tingali rujukan pangajaran anu dianggo.",
    "Lihat detail": "Tingali wincikan",
    "Putar pelafalan": "Puter lafal",
    "Klik ungkapan untuk mendengarkan pelafalan": "Klik ungkara kanggo ngadangukeun lafalna",
    "Sedang diputar": "Nuju diputer",
    "Browser ini belum mendukung suara.": "Panyungsi ieu teu acan ngadukung sora.",
    "Suara tidak dapat diputar di perangkat ini.": "Sora teu tiasa diputer dina alat ieu.",
    "Suara pelafalan": "Sora lafal",
    "Pilihan suara bergantung pada dukungan Bahasa Sunda atau Indonesia di perangkat.": "Pilihan sora gumantung kana pangrojong Basa Sunda atanapi Basa Indonésia dina alat.",
    "Permisi": "Punten",
    "Terima kasih": "Hatur nuhun",
    "Apa bedanya kata “abdi” dan “urang”?": "Naon bédana kecap “abdi” sareng “urang”?",
    "Keduanya berarti “saya”, tetapi penggunaannya bergantung pada konteks.": "Duanana hartina “abdi”, tapi pamakéanana gumantung kana kontéks.",
    "Pelajari Bahasa Sunda dan Aksara Sunda lewat materi terarah, latihan interaktif, dan Tutor AI dengan rujukan pelajaran.": "Diajar Basa Sunda sareng Aksara Sunda ngaliwatan matéri anu runtuy, latihan interaktif, sareng Tutor AI kalayan rujukan pangajaran.",
    "Tepat! Wilujeng enjing berarti selamat pagi.": "Leres! Wilujeng enjing hartina wilujeng enjing.",
    "Coba lagi, wilujeng enjing adalah sapaan pagi.": "Cobi deui, wilujeng enjing téh salam isuk-isuk.",
    "Coba susun aksara": "Cobi susun aksara",
    "Susun “Basa” dari dua karakter berikut.": "Susun “Basa” tina dua karakter ieu.",
    "Ulangi latihan": "Balikan deui latihan",
    Jawabanmu: "Jawaban anjeun",
    "Palet aksara Sunda": "Palét Aksara Sunda",
    "Hapus karakter": "Pupus karakter",
    "Leres! Anjeun nyusun Basa kalayan leres.": "Leres! Anjeun nyusun Basa kalayan leres.",
    "Can leres. Cobi deui susun aksarana.": "Can leres. Cobi deui susun aksarana.",
    "Benar! Kamu berhasil menyusun Basa Sunda.": "Leres! Anjeun parantos tiasa nyusun Basa Sunda.",
    "Belum tepat. Coba susun aksaranya lagi.": "Teu acan leres. Cobi susun deui aksarana.",
    "Pilih karakter untuk mengisi jawaban.": "Pilih karakter kanggo ngeusian jawaban.",
    "Periksa jawaban": "Pariksa jawaban",
    "Belajar Sunda, satu langkah kecil setiap hari.": "Diajar Sunda, saeutik-saeutik unggal dinten.",
    "Pahami ungkapan sehari-hari, kenali Aksara Sunda, lalu latih kemampuanmu lewat materi yang tersusun dan progres yang tersimpan.": "Pahami ungkara sapopoé, wawanohan kana Aksara Sunda, teras latihan ngaliwatan matéri anu disusun tur kamajuan anu disimpen.",
    "Kosakata, ungkapan, dan konteks.": "Kekecapan, ungkara, sareng kontéks.",
    "Baca dan susun karakter Sunda.": "Baca sareng susun karakter Sunda.",
    "Latihan bertahap": "Latihan sacara runtuy",
    "Cek pemahaman setelah belajar.": "Pariksa pamahaman saatos diajar.",
    "Tanya materi dengan rujukan.": "Taroskeun matéri sareng rujukan.",
    "Contoh materi": "Conto matéri",
    "Sapaan dan ungkapan": "Salam sareng ungkara",
    "3 kosakata": "3 kekecapan",
    "Gunakan kata yang tepat, di situasi yang tepat.": "Anggo kecap anu merenah dina kaayaan anu pas.",
    "Pelajari arti, pelafalan, ragam tutur, dan konteks pemakaian melalui unit yang teratur. Setiap pelajaran menggabungkan penjelasan dan contoh yang bisa langsung dicoba.": "Diajar harti, lafal, ragam basa, sareng kontéks pamakéan ngaliwatan unit anu runtuy. Unggal pangajaran ngagabungkeun panjelasan sareng conto anu tiasa langsung dicobian.",
    "Ungkapan yang dekat dengan percakapan sehari-hari": "Ungkara anu raket sareng paguneman sapopoé",
    "Contoh pemakaian beserta artinya": "Conto pamakéan sareng hartina",
    "Audio saat tersedia pada materi": "Audio upami sayogi dina matéri",
    "Lihat kelas Bahasa Sunda": "Tingali kelas Basa Sunda",
    "Kenali bentuknya. Baca bunyinya. Coba menulisnya.": "Wawanohan kana wangunna. Baca sorana. Cobi tuliskeun.",
    "Aksara Sunda punya jalur materi dan latihan tersendiri. Pelajari karakter dan rarangkén secara bertahap, lalu susun jawaban dengan palet aksara di layar.": "Aksara Sunda gaduh matéri sareng latihan anu misah. Diajar karakter sareng rarangkén sacara runtuy, teras susun jawaban nganggo palét aksara dina layar.",
    "Mengenal karakter": "Wawanohan kana karakter",
    "Latihan membaca": "Latihan maca",
    "Latihan menulis": "Latihan nyerat",
    "Jelajahi kelas Aksara Sunda": "Jajah kelas Aksara Sunda",
    "Kenali aksara": "Wawanohan kana aksara",
    "Aksara swara": "Aksara swara",
    "Pratinjau materi": "Sawangan matéri",
    "dan lainnya": "sareng nu sanésna",
    "Belajar dengan bantuan AI": "Diajar dibantuan ku AI",
    "Punya pertanyaan? Mulai dari materi yang sedang kamu pelajari.": "Aya patalékan? Mimitian tina matéri anu keur dipalajari.",
    "Tutor AI membantu menjelaskan materi, melatih percakapan teks, dan memberi saran tulisan. Jawaban menyertakan rujukan materi agar kamu bisa memeriksa kembali konteksnya.": "Tutor AI ngabantosan ngajelaskeun matéri, latihan paguneman téks, sareng masihan saran tulisan. Jawaban dibarengan ku rujukan matéri supados kontéksna tiasa dipariksa deui.",
    "Jawaban AI dapat keliru. Gunakan materi dan rujukan sebagai panduan belajar.": "Jawaban AI tiasa lepat. Anggo matéri sareng rujukan minangka pituduh diajar.",
    "Tutor AI Bahasa Sunda": "Tutor AI Basa Sunda",
    "Belajar dari materi yang diterbitkan": "Diajar tina matéri anu parantos dipedalkeun",
    "Kapan saya memakai kata punten?": "Iraha abdi nganggo kecap punten?",
    "Punten dapat digunakan saat meminta izin atau memulai percakapan dengan sopan.": "Punten tiasa dianggo nalika nyuhunkeun widi atanapi ngamimitian paguneman kalayan sopan.",
    "Rujukan pelajaran": "Rujukan pangajaran",
    "Sapaan dan ungkapan · Bahasa Sunda": "Salam sareng ungkara · Basa Sunda",
    "Belajar terarah, progres tetap tercatat.": "Diajar kalayan puguh, kamajuan tetep kacatet.",
    "Mulai dari topik dasar lalu lanjutkan sesuai ritmemu. Sawala menyimpan pelajaran dan hasil latihan di akunmu.": "Mimitian tina jejer dasar teraskeun nurutkeun wirahma sorangan. Sawala nyimpen pangajaran sareng hasil latihan dina akun anjeun.",
    "Pilih kelas": "Pilih kelas",
    "Bahasa Sunda atau Aksara Sunda.": "Basa Sunda atanapi Aksara Sunda.",
    "Ikuti pelajaran": "Turutan pangajaran",
    "Materi ditata dalam unit yang runtut.": "Matéri disusun dina unit anu runtuy.",
    "Coba latihan": "Cobi latihan",
    "Periksa pemahaman dan baca penjelasan.": "Pariksa pamahaman sareng baca panjelasan.",
    "Lihat progres": "Tingali kamajuan",
    "Kembali ke pelajaran yang terakhir dibuka.": "Balik kana pangajaran anu pamungkas dibuka.",
    "Mulai dari satu pelajaran": "Mimitian tina hiji pangajaran",
    "Sedikit demi sedikit, kamu akan semakin akrab dengan Sunda.": "Saeutik-saeutik, anjeun bakal beuki wawuh kana Basa Sunda.",
    "Buat akun untuk menyimpan progres dan melanjutkan kapan saja.": "Jieun akun kanggo nyimpen kamajuan sareng neraskeun iraha waé.",
    "Buat akun gratis": "Jieun akun gratis",
    "Ruang belajar Bahasa Sunda dan Aksara Sunda yang tertata untuk pelajar.": "Rohangan diajar Basa Sunda sareng Aksara Sunda anu disusun kanggo murid.",
    Jelajahi: "Jajah",
    "Fitur belajar": "Fitur diajar",
    Akun: "Akun",
    "Materi dan kosakata": "Matéri sareng kekecapan",
    "Latihan aksara": "Latihan aksara",
    "Dengarkan pelafalan": "Dangukeun lafal",
    "Latihan kosakata": "Latihan kekecapan",
    "Apa arti “wilujeng enjing”?": "Naon hartina “wilujeng enjing”?",
    "Selamat pagi": "Wilujeng enjing",
    "Selamat malam": "Wilujeng wengi",
    "Rujukan dari materi belajar": "Rujukan tina matéri diajar",
    "Wilujeng sumping,": "Wilujeng sumping,",
    "Lanjutkan langkah belajar Bahasa dan Aksara Sunda hari ini.": "Teruskeun diajar Basa sareng Aksara Sunda dinten ieu.",
    "Lihat progres saya": "Tingali kamajuan abdi",
    "BELAJAR SESUAI LANGKAHMU": "DIAJAR NURUTKEUN LÉNGKAH SORANGAN",
    "Progres keseluruhan": "Kamajuan sakabéhna",
    "KURIKULUM BELAJAR": "KURIKULUM DIAJAR",
    "Pilih kelas belajarmu": "Pilih kelas diajar anjeun",
    "Bahasa & aksara terpisah": "Basa & aksara dipisah",
    "Kelas belajar belum tersedia.": "Kelas diajar teu acan sayogi.",
    "PELAJARAN TERAKHIR": "PANGAJARAN PANGANYARNA",
    "Buka pelajaran": "Buka pangajaran",
    "Belum ada pelajaran yang dibuka.": "Teu acan aya pangajaran nu dibuka.",
    "Butuh teman belajar?": "Peryogi rerencangan diajar?",
    "Tanyakan materi atau latih percakapan bersama Tutor AI.": "Taroskeun matéri atanapi latihan paguneman sareng Tutor AI.",
    "Buka Tutor AI": "Buka Tutor AI",
    "LATIHAN KHUSUS": "LATIHAN HUSUS",
    "Ruang Aksara Sunda": "Rohangan Aksara Sunda",
    "RUANG BELAJAR BAHASA & AKSARA": "ROHANGAN DIAJAR BASA & AKSARA",
    "Kenali Bahasa Sunda, satu pelajaran setiap kali.": "Wawanohan kana Basa Sunda, hiji pangajaran saban waktos.",
    "Dari kosakata yang dipakai sehari-hari sampai bentuk Aksara Sunda. Pilih kelas, pelajari materinya, lalu uji pemahaman dengan latihan.": "Ti kekecapan sapopoé dugi ka wangun Aksara Sunda. Pilih kelas, pelajari matérina, teras cobian latihan.",
    "Belajar mandiri, sesuai langkah Anda.": "Diajar mandiri, nurutkeun léngkah anjeun.",
    "Apa yang akan dipelajari?": "Naon nu badé dipelajari?",
    "BAHASA SUNDA": "BASA SUNDA",
    "Kata, ungkapan, dan konteks.": "Kecap, ungkara, sareng kontéks.",
    "Pelajari arti, cara mengucapkan, dan kapan sebuah ungkapan digunakan.": "Pelajari harti, cara ngucapkeun, sareng iraha hiji ungkara dianggo.",
    "Setiap materi disusun dalam kelas belajar": "Unggal matéri disusun dina kelas diajar",
    "Unit → Pelajaran → Latihan": "Unit → Pangajaran → Latihan",
    "AKSARA SUNDA": "AKSARA SUNDA",
    "Kenali, baca, lalu susun aksara.": "Wawanohan, baca, teras susun aksara.",
    "Belajar dengan arah yang jelas.": "Diajar kalayan arah nu écés.",
    "Dua kelas belajar terpisah membantu Anda memahami bahasa dan aksara sesuai urutannya. Progres tersimpan, sehingga Anda bisa kembali tepat ke pelajaran terakhir. Materi dibuka setelah ditinjau oleh pengelola.": "Dua kelas diajar nu dipisah ngabantosan anjeun ngartos basa sareng aksara sacara runtuy. Kamajuan disimpen sangkan tiasa neraskeun pangajaran pamungkas. Matéri dibuka saatos ditinjau ku pangurus.",
    "Bahasa dan aksara, dipelajari dengan cermat.": "Basa sareng aksara, dipelajari kalayan taliti.",
    "KELAS BELAJAR ·": "KELAS DIAJAR ·",
    "Kelas Belajar": "Kelas Diajar",
    "KURIKULUM": "KURIKULUM",
    "Daftar unit & pelajaran": "Daptar unit & pangajaran",
    "Pelajari materi sesuai urutan atau buka topik yang ingin ditinjau.": "Pelajari matéri sacara runtuy atanapi buka jejer nu badé ditingali.",
    "PELAJARAN": "PANGAJARAN",
    "Belum ada pelajaran terbit dalam unit ini.": "Teu acan aya pangajaran medal dina unit ieu.",
    "Materi sedang disiapkan": "Matéri nuju disiapkeun",
    "Unit akan muncul setelah diterbitkan oleh admin.": "Unit bakal muncul saatos dipedalkeun ku pangurus.",
    "PROGRES KELAS": "KAMAJUAN KELAS",
    "Lihat semua progres": "Tingali sadaya kamajuan",
    "Belajar lewat latihan": "Diajar ngaliwatan latihan",
    "Setiap pelajaran dapat memuat latihan untuk mencoba materi yang baru dibaca.": "Unggal pangajaran tiasa ngandung latihan pikeun nyobian matéri nu nembe dibaca.",
    "Ruang latihan aksara": "Rohangan latihan aksara",
    "KONTEKS PEMAKAIAN": "KONTÉKS PAMAKÉAN",
    "Dengarkan": "Dengekeun",
    "Audio tidak dapat diputar di browser ini.": "Audio teu tiasa diputer dina panyungsi ieu.",
    "· PELAJARAN": "· PANGAJARAN",
    "Isi pelajaran belum tersedia.": "Eusi pangajaran teu acan sayogi.",
    "Uji pemahaman": "Cobian pamahaman",
    "Kerjakan latihan untuk melihat jawaban dan penjelasannya.": "Pigawé latihan pikeun ningali jawaban sareng panjelasanana.",
    "Kembali ke kelas": "Balik ka kelas",
    "Dalam pelajaran ini": "Dina pangajaran ieu",
    "bagian materi ·": "bagian matéri ·",
    "Selesai membaca?": "Parantos réngsé maca?",
    "Tandai pelajaran selesai agar progres belajar tersimpan.": "Tandaan pangajaran parantos réngsé sangkan kamajuan diajar disimpen.",
    "JEJAK BELAJAR": "LALAMPAHAN DIAJAR",
    "Progres belajar": "Kamajuan diajar",
    "Kembali ke pelajaran yang sudah dimulai dan tinjau hasil latihan Anda.": "Balik deui ka pangajaran nu parantos dimimitian sareng tingali hasil latihan anjeun.",
    "PELAJARAN SELESAI": "PANGAJARAN RÉNGSÉ",
    "SEDANG DIPELAJARI": "NUJU DIPALAJARI",
    "LATIHAN DIKERJAKAN": "LATIHAN DIPIGAWÉ",
    "Belum memulai pelajaran": "Teu acan ngamimitian pangajaran",
    "Pilih satu kelas belajar untuk membuka pelajaran pertama Anda.": "Pilih hiji kelas diajar pikeun muka pangajaran munggaran anjeun.",
    "Riwayat latihan": "Sajarah latihan",
    "jawaban benar": "jawaban leres",
    "Belum ada hasil latihan": "Teu acan aya hasil latihan",
    "Latihan akan muncul di sini setelah Anda mengerjakannya dari halaman pelajaran.": "Latihan bakal muncul di dieu saatos anjeun migawéna tina kaca pangajaran.",
    "Hasil latihan": "Hasil latihan",
    "JAWABAN BENAR": "JAWABAN LERES",
    "Baca penjelasan tiap soal sebelum mencoba lagi.": "Baca panjelasan unggal patalékan sateuacan nyobian deui.",
    "Tinjauan jawaban": "Tinjauan jawaban",
    "Jawaban Anda": "Jawaban anjeun",
    "Coba lagi": "Cobian deui",
    "RUANG LATIHAN": "ROHANGAN LATIHAN",
    "Latihan ini belum memiliki soal. Kembali ke pelajaran dan coba lagi nanti.": "Latihan ieu teu acan gaduh patalékan. Balik ka pangajaran sareng cobian deui engké.",
    "Ketuk bagian sesuai urutan. Gunakan Hapus urutan untuk memulai kembali.": "Toél bagian nurutkeun runtuyan. Anggo Pupus runtuyan kanggo ngamimitian deui.",
    "Hapus urutan": "Pupus runtuyan",
    "Palet aksara · pilih karakter atau gunakan papan ketik": "Palét aksara · pilih karakter atanapi anggo papan ketik",
    "Soal berikutnya": "Patalékan salajengna",
    "Sebelumnya": "Saméméhna",
    "Progres latihan": "Kamajuan latihan",
    "Petunjuk": "Pituduh",
    "Kembali ke pelajaran": "Balik ka pangajaran",
    "Soal": "Patalékan",
    "SOAL": "PATALÉKAN",
    "soal": "patalékan",
    "Pelajaran": "Pangajaran",
    "pelajaran": "pangajaran",
    "unit": "unit",
    "dari": "tina",
    "selesai": "réngsé",
    "Latihan Aksara": "Latihan Aksara",
    "Mengenal dan menulis Aksara Sunda": "Wawanohan sareng nyerat Aksara Sunda",
    "Pilih latihan dari materi yang tersedia. Kerjakan soal baca, susun, dan tulis aksara sesuai langkah belajar Anda.": "Pilih latihan tina matéri nu sayogi. Pigawé patalékan maca, nyusun, sareng nyerat aksara nurutkeun léngkah diajar anjeun.",
    "PILIH LATIHAN": "PILIH LATIHAN",
    "Semua latihan aksara": "Sadaya latihan aksara",
    "PERPUSTAKAAN MATERI": "PERPUSTAKAAN MATÉRI",
    "Cari materi belajar": "Téangan matéri diajar",
    "Cari": "Téangan",
    "Belum ada materi yang cocok. Coba kata kunci lain atau buka": "Teu aya matéri nu cocog. Coba kecap konci sanés atanapi buka",
    "kelas belajar": "kelas diajar",
    "Tanyakan materi, berlatih percakapan, atau minta saran tulisan. Periksa kembali jawaban dengan rujukan pelajaran.": "Taroskeun matéri, latihan paguneman, atanapi nyuhunkeun saran tulisan. Pariksa deui jawaban ku rujukan pangajaran.",
    "PILIH CARA BELAJAR": "PILIH CARA DIAJAR",
    "Belajar dari materi": "Diajar tina matéri",
    "Rujukan pelajaran muncul bersama jawaban jika tersedia.": "Rujukan pangajaran muncul sareng jawaban upami sayogi.",
    "Lihat kelas": "Tingali kelas",
    "PERTANYAAN ANDA": "PATALÉKAN ANJEUN",
    "JAWABAN AI": "JAWABAN AI",
    "Rujukan materi:": "Rujukan matéri:",
    "Mulai percakapan baru": "Mimitian paguneman énggal",
    "Ajukan pertanyaan tentang materi yang sudah diterbitkan untuk mulai belajar bersama tutor.": "Ajukeun patalékan ngeunaan matéri nu parantos dipedalkeun kanggo ngamimitian diajar sareng tutor.",
    "Jenis bantuan": "Jinis pitulung",
    "Tanya jawab materi": "Patalékan matéri",
    "Latihan percakapan teks": "Latihan paguneman téks",
    "Saran tulisan": "Saran tulisan",
    "Pesan Anda": "Talatah anjeun",
    "Tutor AI dapat membuat kekeliruan. Tinjau rujukan pelajaran sebelum menerapkan jawaban.": "Tutor AI tiasa lepat. Tinjau rujukan pangajaran sateuacan ngalarapkeun jawaban.",
    "unit ·": "unit ·",
    "pelajaran ·": "pangajaran ·",
    "blok ·": "blok ·",
    "Materi (": "Matéri (",
    "Latihan (": "Latihan (",
    "Latihan": "Latihan",
    "Buka kelas": "Buka kelas",
    "LATIHAN": "LATIHAN",
    "soal ·": "patalékan ·",
    "Latihan aksara belum diterbitkan. Buka kelas Aksara Sunda untuk melihat materi yang sudah tersedia.": "Latihan aksara teu acan dipedalkeun. Buka kelas Aksara Sunda kanggo ningali matéri nu parantos sayogi.",
    "Mulai dari materi": "Mimitian tina matéri",
    "Kenali bentuk aksara dan cara membacanya sebelum menjawab soal.": "Wawanohan kana wangun aksara sareng cara macana sateuacan ngajawab patalékan.",
    "Buka kelas Aksara": "Buka kelas Aksara",
    "Gunakan palet aksara pada soal menulis jika papan ketik belum mendukung.": "Anggo palét aksara dina patalékan nyerat upami papan ketik teu acan ngadukung.",
    "Selesai": "Réngsé",
    "Sedang dipelajari": "Nuju dipalajari",
    "Cari pelajaran, kosakata, atau aksara": "Téangan pangajaran, kekecapan, atanapi aksara",
    "Masukkan kata kunci untuk mencari materi yang sudah terbit.": "Lebetkeun kecap konci kanggo milarian matéri nu parantos dipedalkeun.",
    "Tandai selesai": "Tandaan réngsé",
    "Tanya materi": "Taroskeun matéri",
    "Latihan percakapan": "Latihan paguneman",
    "Pilih bantuan": "Pilih pitulung",
    "Tulis pertanyaan tentang pelajaran yang tersedia...": "Tulis patalékan ngeunaan pangajaran nu sayogi...",
    "Menyiapkan jawaban...": "Nuju nyiapkeun jawaban...",
    "Kirim pesan": "Kirim talatah",
    "Latihan Aksara Sunda": "Latihan Aksara Sunda",
    "Urutan jawaban Anda akan muncul di sini.": "Runtuyan jawaban anjeun bakal muncul di dieu.",
    "Kirim jawaban": "Kirim jawaban",
    "Ketuk karakter pada palet aksara untuk menyusun jawaban, atau ketik langsung.": "Toél karakter dina palét aksara kanggo nyusun jawaban, atanapi ketik langsung.",
    "Baca soal dengan teliti. Jawaban dan penjelasan muncul setelah seluruh soal dikirim.": "Baca patalékan kalayan taliti. Jawaban sareng panjelasan muncul saatos sadaya patalékan dikirim.",
    "Benar": "Leres",
    "Perlu dipelajari lagi": "Peryogi dipalajari deui",
    "Tidak dijawab": "Teu dijawab",
    "AKSARA": "AKSARA",
    "BAHASA": "BASA",
    "Berjalan": "Nuju lumangsung",
    "Mulai": "Mimitian",
};

export function translateUi(text: string, locale: UiLocale): string {
    return locale === "su" ? (su[text] ?? text) : text;
}

export function t(text: string): string {
    return translateUi(text, typeof document !== "undefined" && document.documentElement.lang === "su" ? "su" : "id");
}

export function useUiLanguage() {
    const { uiLocale } = usePage<{ uiLocale?: UiLocale }>().props;
    const locale: UiLocale = uiLocale === "su" ? "su" : "id";
    return { locale, t: (text: string) => translateUi(text, locale) };
}
