import { usePage } from "@inertiajs/react";

export type UiLocale = "id" | "su";

const su: Record<string, string> = {
    "Bahasa Sunda": "Basa Sunda",
    "Lewati ke konten utama": "Luncat ka eusi utama",
    "KELAS BELAJAR": "KELAS DIAJAR",
    "AKUN SAWALA": "AKUN SAWALA",
    "Ruang belajar": "Rohangan diajar",
    "Kembali ke": "Balik ka",
    "Kembali ke daftar modul": "Balik ka daptar modul",
    "MODUL": "MODUL",
    "MODUL AKTIF": "MODUL NUJU DIAJAR",
    "MATERI DALAM MODUL": "MATÉRI DINA MODUL",
    "MATERI BELAJAR": "MATÉRI DIAJAR",
    "Pilih modul belajar": "Pilih modul diajar",
    "Buka satu modul untuk melihat semua materi di dalamnya tanpa tercampur dengan modul lain.": "Buka hiji modul pikeun ningali sadaya matéri di jerona tanpa pacampur sareng modul sanés.",
    "Buka modul": "Buka modul",
    "Progres modul": "Kamajuan modul",
    "materi selesai": "matéri réngsé",
    "Materi": "Matéri",
    "Materi dalam modul": "Matéri dina modul",
    "Buka daftar materi": "Buka daptar matéri",
    "Belum ada materi terbit": "Teu acan aya matéri medal",
    "Belum ada materi terbit dalam modul ini.": "Teu acan aya matéri medal dina modul ieu.",
    "Materi akan muncul di sini setelah diterbitkan oleh pengelola.": "Matéri bakal muncul di dieu saatos dipedalkeun ku pangatur.",
    "Segera hadir": "Moal lami deui",
    Sawala: "Sawala",
    "Aksara Sunda": "Aksara Sunda",
    "Latihan & Aksara": "Latihan & Aksara",
    "Tutor AI": "Tutor AI",
    "Progres Belajar": "Kamajuan Diajar",
    Ringkasan: "Ringkesan",
    "Kelas & Pelajaran": "Kelas & Pangajaran",
    "Kosakata & Konteks": "Kekecapan & Kontéks",
    "Materi belajar": "Matéri diajar",
    "KELAS AKTIF": "KELAS NUJU DIAJAR",
   "Progres kelas": "Kamajuan kelas",
    "Pelajaran dalam unit": "Pangajaran dina unit",
   "Lihat daftar kelas": "Tingali daptar kelas",
    "Daftar modul & materi": "Daptar modul & matéri",
    "bagian materi": "bagian matéri",
    "Video materi": "Video matéri",
    "Tonton penjelasan materi": "Tingali panjelasan matéri",
    "Video bersifat pelengkap. Materi tertulis tetap tersedia di bawah.": "Video ieu minangka panglengkep. Matéri tinulis tetep aya di handap.",
    "Isi materi ini": "Eusi matéri ieu",
    "Pilih bagian untuk langsung menuju penjelasannya.": "Pilih bagian pikeun langsung ningali panjelasanana.",
    "Daftar bagian materi": "Daptar bagian matéri",
    "Navigasi antar pelajaran": "Pindah antar pangajaran",
    "Tautan video YouTube (opsional)": "Tautan video YouTube (opsional)",
    "Video akan tampil di halaman materi. Tempel tautan youtube.com atau youtu.be.": "Video bakal dipintonkeun dina kaca matéri. Tempel tautan youtube.com atanapi youtu.be.",
    "Kumpulan Aksara Sunda": "Kumpulan Aksara Sunda",
    "Kelola karakter Aksara Sunda yang digunakan di materi pelajaran.": "Atur karakter Aksara Sunda anu dianggo dina matéri pangajaran.",
    "Tambah aksara": "Tambah aksara",
    "Cari aksara, latin, atau pelajaran...": "Pilarian aksara, latin, atanapi pangajaran...",
    "Daftar aksara": "Daptar aksara",
    "Kelola aksara melalui blok materi yang tersimpan pada pelajaran.": "Atur aksara ngaliwatan blok matéri anu disimpen dina pangajaran.",
    "Tanpa nama": "Tanpa nami",
    "Arti belum ditulis": "Harti teu acan ditulis",
    Menampilkan: "Nembongkeun",
    Berikutnya: "Salajengna",
    "Kelas terpilih": "Kelas anu dipilih",
    "Status kelas": "Status kelas",
    "Nama kelas...": "Nami kelas...",
    "Unit terpilih": "Unit anu dipilih",
    "Pilih unit pembelajaran": "Pilih unit pangajaran",
    "Cari pelajaran": "Pilarian pangajaran",
    "Cari pelajaran dalam unit...": "Pilarian pangajaran dina unit...",
    "Lihat soal": "Tingali soal",
    "Belum ada soal": "Teu acan aya soal",
    "Audio materi": "Audio matéri",
    "Entri tanpa judul": "Éntri tanpa judul",
    "Ubah aksara": "Robih aksara",
    "Tidak ada aksara yang cocok": "Teu aya aksara anu cocog",
    "Belum ada aksara Sunda": "Teu acan aya aksara Sunda",
    "Coba kata pencarian lain.": "Cobian kecap pilarian sanés.",
    "Tambahkan blok aksara pada pelajaran di kelas Aksara Sunda untuk mengisi kumpulan ini.":
        "Tambahkeun blok aksara dina pangajaran di kelas Aksara Sunda pikeun ngeusian kumpulan ieu.",
    "Buka kelas Aksara Sunda": "Buka kelas Aksara Sunda",
    "Latihan & Soal": "Latihan & Patalékan",
    "Audio & Media": "Audio & Média",
    "Pelajar & Progres": "Murid & Kamajuan",
    Operasional: "Operasional",
    "Laporan & Analitik": "Laporan & Analitik",
    "Pengaturan Tutor AI": "Setélan Tutor AI",
    "Umpan Balik": "Eupan Balik",
    "Kirim umpan balik": "Kirim eupan balik",
    "Aktivitas Tutor AI 30 hari": "Kagiatan Tutor AI 30 dinten",
    percakapan: "paguneman",
    "Jumlah pesan dalam 30 hari terakhir.": "Jumlah pesen dina 30 dinten panungtung.",
    "Riwayat Tutor AI ditampilkan per 100 pesan.": "Riwayat Tutor AI ditingalikeun 100 pesen sakali.",
    "Kembali ke percakapan terbaru": "Balik ka paguneman panganyarna",
    "Muat percakapan sebelumnya": "Muat paguneman saméméhna",
    "Lebih baru": "Langkung énggal",
    "Lebih lama": "Langkung lami",
    "Riwayat ditampilkan 25 per halaman.": "Riwayat ditingalikeun 25 data unggal kaca.",
    "Laporan & analitik": "Laporan & analitik",
    "Pantau aktivitas belajar, penyelesaian kelas, dan hasil latihan.": "Tingali kagiatan diajar, pangajaran anu réngsé, sareng hasil latihan.",
    "Atur cara tutor menjawab dan koneksi penyedia AI.": "Atur cara tutor ngawaler sareng sambungan panyadia AI.",
    "Umpan balik": "Eupan balik",
    "Tinjau laporan, saran, dan masukan yang dikirim pelajar.": "Tingali laporan, saran, sareng eupan balik ti murid.",
    "Semua akun pelajar": "Sadaya akun murid",
    "Aktif 7 hari": "Aktif 7 dinten",
    "Membuka materi atau latihan": "Muka matéri atanapi latihan",
    "Pelajaran selesai · 30 hari": "Pangajaran réngsé · 30 dinten",
    "Akurasi latihan · 30 hari": "Katepatan latihan · 30 dinten",
    "Penyelesaian dalam 30 hari terakhir": "Pangajaran anu diréngsékeun dina 30 dinten panungtung",
    "Jumlah pelajaran yang dituntaskan di setiap kelas dalam 30 hari terakhir.": "Jumlah pangajaran anu diréngsékeun dina unggal kelas dina 30 dinten panungtung.",
    "Urutan berdasarkan akurasi terendah selama 30 hari terakhir.": "Diurutkeun tina katepatan panghandapna dina 30 dinten panungtung.",
    "Urutan berdasarkan akurasi terendah selama 30 hari terakhir. Aktivitas tampil setelah terkumpul minimal 5 percobaan.":
        "Diurutkeun tina katepatan panghandapna dina 30 dinten panungtung. Kagiatan muncul sanggeus aya sahenteuna 5 kasempetan.",
    "Aktivitas latihan tampil setelah masing-masing menerima minimal 5 percobaan agar ringkasan lebih mewakili.":
        "Kagiatan latihan muncul sanggeus masing-masing meunang sahenteuna 5 kasempetan supaya ringkesanana leuwih ngawakilan.",
    "Total dari semua pelajar": "Jumlah ti sadaya murid",
    "Akurasi latihan": "Katepatan latihan",
    "percobaan terkumpul": "percobaan kacatet",
    "Penyelesaian per kelas": "Pangajaran réngsé per kelas",
    "Jumlah pelajaran yang dituntaskan di setiap kelas.": "Jumlah pangajaran anu diréngsékeun dina unggal kelas.",
        "Latihan yang perlu ditinjau": "Latihan anu kedah ditingali",
    "Urutan berdasarkan akurasi terendah dari percobaan pelajar.": "Diurutkeun tina katepatan panghandapna dumasar kana hasil latihan murid.",
    percobaan: "percobaan",
    "Latihan akan muncul setelah pelajar mengirim jawabannya.": "Latihan bakal muncul saatos murid ngirimkeun jawaban.",
    "percakapan Tutor AI": "paguneman Tutor AI",
    "Jumlah pesan yang pernah tercatat.": "Jumlah pesen anu parantos kacatet.",
    "Status tutor": "Status tutor",
    Aktif: "Hurung",
    Dinonaktifkan: "Dipareuman",
    "Pesan hari ini": "Pesen dinten ieu",
    "Token hari ini": "Token dinten ieu",
    "Konfigurasi tutor": "Konfigurasi tutor",
    "Uji koneksi": "Uji sambungan",
    "Menguji koneksi...": "Nuju nguji sambungan...",
    "Periksa URL API dan nama model.": "Pariksa URL API sareng nami modél.",
    "Kunci API dikirim ke server Sawala dan tidak pernah diberikan ke browser pelajar.": "Konci API dikirim ka server Sawala sareng teu kantos dipasihkeun ka browser murid.",
    "Uji koneksi mengirim satu permintaan singkat dengan pengaturan saat ini tanpa menyimpan perubahan.": "Uji sambungan ngirim hiji pamundut pondok nganggo setélan ayeuna tanpa nyimpen parobahan.",
    "Masukkan API key atau konfigurasi kunci di server sebelum menguji koneksi.": "Lebetkeun API key atanapi atur konci dina server sateuacan nguji sambungan.",
    "Koneksi ditolak penyedia AI. Periksa API key dan izin model.": "Sambungan ditolak ku panyadia AI. Pariksa API key sareng idin modél.",
    "Endpoint tidak ditemukan. Periksa URL API; URL dasar harus menyediakan /chat/completions.": "Endpoint teu kapanggih. Pariksa URL API; URL dasar kedah nyayogikeun /chat/completions.",
    "Penyedia AI membatasi permintaan. Periksa kuota atau coba lagi nanti.": "Panyadia AI ngawatesan pamundut. Pariksa kuota atanapi cobian deui engké.",
    "Penyedia AI mengembalikan respons gagal. Periksa URL, model, API key, atau kuota akun.": "Panyadia AI mulangkeun réspon gagal. Pariksa URL, modél, API key, atanapi kuota akun.",
    "Penyedia merespons, tetapi format jawabannya tidak sesuai API chat completions.": "Panyadia ngaréspon, nanging format jawabanana henteu cocog sareng API chat completions.",
    "Server tidak dapat terhubung ke penyedia AI. Periksa URL dan koneksi server.": "Server teu tiasa nyambung ka panyadia AI. Pariksa URL sareng sambungan server.",
    "Koneksi penyedia AI berhasil. Pengaturan ini belum disimpan.": "Sambungan panyadia AI hasil. Setélan ieu teu acan disimpen.",
    "Tutor hanya menggunakan materi pelajaran yang sudah diterbitkan sebagai rujukan jawaban.":
        "Tutor ngan nganggo matéri pangajaran anu parantos diterbitkeun salaku rujukan jawaban.",
    "Kunci tersimpan terenkripsi": "Konci disimpen kalayan énkripsi",
    "Kunci berasal dari konfigurasi server": "Konci dicandak tina konfigurasi server",
    "Kunci belum dikonfigurasi": "Konci teu acan diatur",
    "API key belum diatur": "API key teu acan diatur",
    "URL API": "URL API",
    "Nama model": "Nami modél",
    "API key baru (opsional)": "API key énggal (pilihan)",
    "Kosongkan untuk mempertahankan kunci saat ini": "Kosongkeun pikeun tetep nganggo konci ayeuna",
    "Kunci disimpan terenkripsi dan tidak pernah ditampilkan kembali.": "Konci disimpen kalayan énkripsi sareng moal ditingalikeun deui.",
    "Hapus kunci tersimpan": "Pupus konci anu disimpen",
    "Kunci tersimpan akan dihapus": "Konci anu disimpen bakal dipupus",
    "Bahasa jawaban": "Basa jawaban",
    "Ikuti bahasa akun pelajar": "Turutan basa akun murid",
    "Gaya jawaban": "Gaya jawaban",
    "Hangat dan ringkas": "Someah sareng ringkes",
    "Sangat ringkas": "Pondok pisan",
    "Bertahap dengan contoh": "Laun-laun sareng conto",
    "Batas token jawaban": "Wates token jawaban",
    "Aktifkan Tutor AI untuk pelajar": "Hurungkeun Tutor AI kanggo murid",
    "Simpan pengaturan": "Simpen setélan",
    "Percakapan pelajar tidak menggunakan kunci API yang dikirim dari browser.": "Paguneman murid henteu nganggo API key anu dikirim tina panyungsi.",
    "Pengaturan Tutor AI berhasil disimpan.": "Setélan Tutor AI parantos disimpen.",
    "Status tindak lanjut": "Status tindak lanjut",
    "Masukan tidak ditemukan": "Eupan balik teu kapendak",
    "Belum ada umpan balik": "Teu acan aya eupan balik",
    "Masukan dari pelajar akan muncul di sini setelah dikirim.": "Eupan balik ti murid bakal muncul di dieu saatos dikirim.",
    "Status masukan diperbarui.": "Status eupan balik parantos dirobih.",
    "Cari nama pelajar atau isi umpan balik...": "Pilarian nami murid atanapi eusi eupan balik...",
    "Lihat perkembangan tindak lanjut dari pengelola.": "Tingali kamajuan tindak lanjut ti pangurus.",
    "Bantu Sawala jadi lebih baik": "Bantosan Sawala janten langkung saé",
    "Laporkan materi yang perlu diperbaiki, kendala teknis, atau ide untuk pengalaman belajar.":
        "Laporkeun matéri anu kedah dibenerkeun, masalah téknis, atanapi ide pikeun pangalaman diajar.",
    "Kirim masukan": "Kirim eupan balik",
    "Ceritakan dengan jelas agar tim dapat menindaklanjutinya.": "Jelaskeun kalayan écés supados tim tiasa ngaréngsékeunana.",
    "Jenis masukan": "Jinis eupan balik",
    "Masalah teknis": "Masalah téknis",
    "Ide atau saran": "Ide atanapi saran",
    Pesan: "Pesen",
    "Tuliskan bagian yang dimaksud dan apa yang Anda harapkan...": "Tulis bagian anu dimaksud sareng harepan anjeun...",
    karakter: "karakter",
    "Mengirim...": "Nuju ngirim...",
    "Terima kasih, masukan Anda sudah terkirim.": "Hatur nuhun, eupan balik anjeun parantos dikirim.",
    "Kembali ke beranda": "Balik ka tepas",
    "Masukan saya": "Eupan balik abdi",
    "Belum ada masukan terkirim": "Teu acan aya eupan balik anu dikirim",
    "Setelah mengirim masukan, status tindak lanjut akan tampil di sini.": "Sanggeus ngirim eupan balik, status tindak lanjut bakal muncul di dieu.",
    Diterima: "Katampi",
    "Sedang ditinjau": "Nuju ditingali",
    Ditindaklanjuti: "Parantos ditindaklanjuti",
    "Bahasa & Aksara Sunda": "Basa & Aksara Sunda",
    "Navigasi admin": "Navigasi pangurus",
    "Navigasi belajar": "Navigasi diajar",
    "Bantuan belajar": "Pitulung diajar",
    "Bingung tentang tata bahasa atau aksara? Tanyakan kepada tutor.": "Teu acan ngartos tata basa atanapi aksara? Taroskeun ka tutor.",
    "Buka tutor": "Buka tutor",
    "Pengaturan akun": "Setélan akun",
    "Pengaturan & Bahasa": "Setélan & Basa",
    Keluar: "Kaluar",
    "Buka menu": "Buka ménu",
    "Buka menu admin": "Buka ménu pangurus",
    "Pilih halaman": "Pilih kaca",
    "Cari materi": "Téangan matéri",
    "Cari kosakata, aksara, atau pelajaran": "Téangan kekecapan, aksara, atanapi pangajaran",
    "pelajaran selesai": "pangajaran réngsé",
    latihan: "latihan",
    "Profil & pengaturan": "Profil & setélan",
    "Atur profil, bahasa tampilan, dan keamanan akun Anda.": "Atur profil, basa tampilan, sareng kaamanan akun anjeun.",
    "Menu profil": "Ménu profil",
    Pengaturan: "Setélan",
    Beranda: "Tepas",
    Profil: "Profil",
    "Informasi profil": "Inpormasi profil",
    "Nama dan alamat email untuk akun Sawala Anda.": "Nami sareng alamat surélék kanggo akun Sawala anjeun.",
    "Kelola identitas dan preferensi bahasa akun Anda.": "Atur idéntitas sareng karesep basa akun anjeun.",
    "Kelola kata sandi dan perlindungan akun Anda.": "Atur kecap akses sareng panangtayungan akun anjeun.",
    "Ubah bahasa menu dan petunjuk aplikasi. Materi tetap memakai bahasa aslinya.": "Robih basa ménu sareng pituduh aplikasi. Matéri tetep nganggo basa aslina.",
    Keamanan: "Kaamanan",
    "Bahasa tampilan": "Basa tampilan",
    "Pilih bahasa untuk menu dan petunjuk aplikasi. Materi pelajaran tetap menggunakan bahasa aslinya.":
        "Pilih basa pikeun ménu sareng pituduh aplikasi. Eusi pangajaran tetep nganggo basa aslina.",
    "Bahasa Indonesia": "Basa Indonésia",
    "Bahasa berhasil diubah.": "Basa parantos dirobih.",
    "Pengaturan profil": "Setélan profil",
    "Keamanan akun": "Kaamanan akun",
    "Ubah kata sandi": "Robih kecap akses",
    "Gunakan kata sandi yang kuat dan tidak digunakan di tempat lain": "Anggo kecap akses anu kuat sareng teu dianggo di tempat sanés",
    "Kata sandi saat ini": "Kecap akses ayeuna",
    "Kata sandi baru": "Kecap akses énggal",
    "Ulangi kata sandi baru": "Balikan kecap akses énggal",
    "Simpan kata sandi": "Simpen kecap akses",
    "Kata sandi": "Kecap akses",
    "Hapus akun": "Pupus akun",
    "Hapus akun dan seluruh data yang terkait.": "Pupus akun sareng sadaya data nu patali.",
    Perhatian: "Perhatosan",
    "Tindakan ini permanen dan tidak dapat dibatalkan.": "Léngkah ieu permanén sareng teu tiasa dibolaykeun.",
    "Yakin ingin menghapus akun?": "Yakin badé mupus akun?",
    "Setelah akun dihapus, seluruh data terkait juga akan dihapus permanen. Masukkan kata sandi untuk mengonfirmasi tindakan ini.":
        "Sanggeus akun dipupus, sadaya data nu patali ogé bakal dipupus permanén. Lebetkeun kecap akses kanggo mastikeun léngkah ieu.",
    "Autentikasi dua faktor": "Auténtikasi dua faktor",
    "Atur lapisan keamanan tambahan untuk akun Anda.": "Atur lapisan kaamanan tambahan kanggo akun anjeun.",
    "Saat masuk, masukkan kode sekali pakai dari aplikasi autentikasi di ponsel Anda.": "Nalika lebet, lebetkeun kode sakali anggo tina aplikasi auténtikasi dina telepon anjeun.",
    "Matikan autentikasi dua faktor": "Pareuman auténtikasi dua faktor",
    "Kode sekali pakai dari aplikasi autentikasi akan diminta setiap kali Anda masuk.": "Kode sakali anggo tina aplikasi auténtikasi bakal dipénta saban anjeun lebet.",
    "Lanjutkan pengaturan": "Teraskeun pangaturan",
    "Aktifkan autentikasi dua faktor": "Hurungkeun auténtikasi dua faktor",
    "Autentikasi dua faktor aktif": "Auténtikasi dua faktor hurung",
    "Autentikasi dua faktor aktif. Pindai kode QR atau masukkan kunci pengaturan ke aplikasi autentikasi Anda.":
        "Auténtikasi dua faktor hurung. Pindai kode QR atanapi lebetkeun konci pangaturan kana aplikasi auténtikasi anjeun.",
    "Verifikasi kode autentikasi": "Vérifikasi kode auténtikasi",
    "Masukkan kode 6 digit dari aplikasi autentikasi Anda.": "Lebetkeun kode 6 digit tina aplikasi auténtikasi anjeun.",
    "Pindai kode QR atau masukkan kunci pengaturan ke aplikasi autentikasi untuk menyelesaikan pengaktifan.":
        "Pindai kode QR atanapi lebetkeun konci pangaturan kana aplikasi auténtikasi kanggo ngaréngsékeun panghurungan.",
    Tutup: "Tutup",
    "atau masukkan kodenya secara manual": "atanapi lebetkeun kodena sacara manual",
    Kembali: "Balik",
    Konfirmasi: "Pastikeun",
    "Kode pemulihan autentikasi dua faktor": "Kode pamulihan auténtikasi dua faktor",
    "Kode ini membantu memulihkan akses jika perangkat autentikasi hilang. Simpan di pengelola kata sandi yang aman.":
        "Kode ieu ngabantosan mulihkeun aksés upami alat auténtikasi leungit. Simpen dina pangatur kecap akses anu aman.",
    "kode pemulihan": "kode pamulihan",
    "Kode pemulihan": "Kode pamulihan",
    "Memuat kode pemulihan": "Nuju ngamuat kode pamulihan",
    "Buat kode baru": "Jieun kode énggal",
    "Setiap kode hanya dapat digunakan sekali dan akan terhapus setelah digunakan. Untuk membuat kode baru, pilih":
        "Saban kode ngan tiasa dianggo sakali sareng bakal dipupus sanggeus dianggo. Kanggo nyieun kode énggal, pilih",
    "di atas.": "di luhur.",
    Sembunyikan: "Sumputkeun",
    Lihat: "Tingali",
    Passkey: "Konci aksés",
    "Kelola passkey untuk masuk tanpa kata sandi.": "Atur konci aksés kanggo lebet tanpa kecap akses.",
    "Belum ada passkey": "Teu acan aya konci aksés",
    "Tambahkan passkey agar dapat masuk tanpa kata sandi.": "Tambihkeun konci aksés supados tiasa lebet tanpa kecap akses.",
    "Browser ini belum mendukung passkey.": "Panyungsi ieu teu acan ngadukung konci aksés.",
    "Tambahkan passkey": "Tambihkeun konci aksés",
    "Nama passkey": "Nami konci aksés",
    "Nama ini membantu Anda mengenali passkey nanti.": "Nami ieu ngabantosan anjeun mikawanoh konci aksés engké.",
    "Contoh: laptop atau ponsel saya": "Conto: laptop atanapi telepon abdi",
    "Mendaftarkan...": "Nuju ngadaptarkeun...",
    "Daftarkan passkey": "Daptarkeun konci aksés",
    Ditambahkan: "Ditambihkeun",
    "Terakhir digunakan": "Panungtung dianggo",
    "Hapus passkey": "Pupus konci aksés",
    "Hapus passkey “": "Pupus konci aksés “",
    "”? Anda tidak dapat lagi menggunakannya untuk masuk.": "”? Anjeun moal tiasa nganggo deui kanggo lebet.",
    "PROFIL SAYA": "PROFIL ABDI",
    Pelajar: "Murid",
    "Perbarui nama dan alamat email Anda": "Robih nami sareng alamat email anjeun",
    Nama: "Nami",
    "Nama lengkap": "Nami lengkep",
    "Alamat email": "Alamat email",
    Simpan: "Simpen",
    "Alamat email Anda belum diverifikasi.": "Alamat email anjeun teu acan diverifikasi.",
    "Kirim ulang email verifikasi.": "Kirim deui email vérifikasi.",
    "Tautan verifikasi baru telah dikirim ke email Anda.": "Tumbu vérifikasi énggal parantos dikirim ka email anjeun.",
    "STUDIO ADMIN / PENGELOLAAN": "STUDIO PANGURUS / PANGATURAN",
    "SAWALA · STUDIO KONTEN": "SAWALA · STUDIO EUSI",
    "Kelola pengalaman belajar yang bermakna.": "Atur pangalaman diajar nu aya mangpaatna.",
    "Susun kelas, lengkapi materi, dan tinjau progres pelajar dari satu ruang kerja.": "Susun kelas, lengkepan matéri, tur tingali kamajuan murid dina hiji rohangan gawé.",
    "Kelola kelas belajar": "Atur kelas diajar",
    "Kelas belajar": "Kelas diajar",
    "terbuka untuk pelajar": "kabuka pikeun murid",
    "Pelajaran siap tayang": "Pangajaran siap dipedalkeun",
    "masih draf atau ditinjau": "masih draf atanapi ditinjau",
    "Aktivitas tersedia di laporan pelajar": "Kagiatan aya dina laporan murid",
    "Kelas yang dikelola": "Kelas nu diatur",
    "Pilih kelas untuk melanjutkan penyusunan materi.": "Pilih kelas pikeun nuluykeun nyusun matéri.",
    "Lihat semua": "Tingali sadayana",
    "Alur penerbitan": "Léngkah medalkeun",
    "Materi harus lengkap dan ditinjau sebelum dibuka untuk pelajar.": "Matéri kedah lengkep tur ditinjau sateuacan dibuka pikeun murid.",
    "Susun pelajaran": "Susun pangajaran",
    "Tambahkan isi materi, contoh, dan latihan.": "Tambihkeun eusi matéri, conto, sareng latihan.",
    "Tinjau konten": "Tinjau eusi",
    "Periksa ragam bahasa, aksara, dan jawaban.": "Pariksa ragam basa, aksara, sareng jawaban.",
    "Terbitkan berurutan": "Pedalkeun sacara runtuy",
    "Pelajaran, unit, lalu kelas belajar.": "Pangajaran, unit, teras kelas diajar.",
    "Kelola kelas": "Atur kelas",
    "Pilih kelas yang dikelola": "Pilih kelas nu diatur",
    "kelas tersedia": "kelas sayogi",
    "Cari kelas": "Téangan kelas",
    "Filter status kelas": "Saring status kelas",
    "Semua status": "Sadayana status",
    "Tidak ada kelas yang cocok. Ubah kata kunci atau status.": "Teu aya kelas nu cocog. Robih kecap konci atanapi status.",
    "Buat kelas": "Jieun kelas",
    "Ubah kelas": "Robih kelas",
    "Unit pembelajaran": "Unit pangajaran",
    "Pilih unit untuk mengatur pelajaran di dalamnya.": "Pilih unit pikeun ngatur pangajaran di jerona.",
    "Tambah unit": "Tambah unit",
    "UNIT TERPILIH": "UNIT KAPILIH",
    "Ubah unit": "Robih unit",
    "Urutan pelajaran": "Runtuyan pangajaran",
    "Tambah pelajaran": "Tambah pangajaran",
    "Hapus filter": "Pupus saringan",
    "Entri kosakata & aksara": "Éntri kekecapan & aksara",
    "Entri berasal dari blok materi pada pelajaran.": "Éntri asalna tina blok matéri dina pangajaran.",
    "Buka kelas belajar": "Buka kelas diajar",
    "Latihan yang tersusun": "Latihan nu parantos disusun",
    "Kelola soal dan kunci jawaban pada latihan yang sudah dibuat.": "Atur patalékan sareng konci jawaban dina latihan nu parantos dijieun.",
    "Tambah soal": "Tambah patalékan",
    "Kelola pelajaran": "Atur pangajaran",
    "Audio pelafalan": "Audio lafal",
    "Berkas audio tersimpan pada blok materi terkait.": "Berkas audio disimpen dina blok matéri nu patali.",
    "Audio tersimpan pada blok materi terkait.": "Audio disimpen dina blok matéri nu patali.",
    "Audio tersimpan": "Audio disimpen",
    "Tambah audio": "Tambah audio",
    "Tambah audio pelafalan": "Tambah audio lafal",
    "Unggah audio": "Unggah audio",
    "Ganti audio": "Ganti audio",
    "Ganti audio pelafalan": "Ganti audio lafal",
    "Unggah audio pelafalan": "Unggah audio lafal",
    "Berkas audio": "Berkas audio",
    "Materi tujuan": "Matéri tujuan",
    "Pilih materi yang akan diberi audio": "Pilih matéri anu badé dipasihan audio",
    "Gunakan materi yang sudah ada": "Anggo matéri nu tos aya",
    "Buat materi baru": "Jieun matéri énggal",
    "Pilih materi yang sudah ada atau buat materi baru, lalu rekam atau unggah audionya.": "Pilih matéri anu tos aya atanapi jieun matéri énggal, teras rékam atanapi unggah audiona.",
    "Pilih pelajaran": "Pilih pangajaran",
    "Tulisan Latin / frasa": "Tulisan Latin / frasa",
    "Contoh: Wilujeng enjing": "Conto: Wilujeng enjing",
    "Arti Bahasa Indonesia (opsional)": "Harti dina basa Indonésia (opsional)",
    "Tulis arti atau konteks materi.": "Tulis harti atanapi kontéks matéri.",
    "Materi baru akan disimpan sebagai entri kosakata pada pelajaran pilihan.": "Matéri énggal bakal disimpen minangka éntri kekecapan dina pangajaran nu dipilih.",
    "audio akan diganti": "audio badé diganti",
    "Audio lama akan diganti setelah audio baru berhasil disimpan.": "Audio lami bakal digentos sanggeus audio énggal hasil disimpen.",
    "Audio akan ditambahkan pada materi ini.": "Audio bakal ditambihkeun kana matéri ieu.",
    "Pilih berkas audio": "Pilih berkas audio",
    "Unggah dari folder": "Unggah tina polder",
    "Pilih rekaman audio dari perangkat Anda.": "Pilih rekaman audio tina alat anjeun.",
    "Rekam langsung": "Rékam langsung",
    "Gunakan mikrofon perangkat untuk merekam pelafalan.": "Anggo mikropon alat pikeun ngarékam lafal.",
    "Pilih materi, lalu pilih untuk merekam suara langsung atau mengunggah berkas audio.": "Pilih matéri, tuluy rékam sora langsung atanapi unggah berkas audio.",
    "Pilih materi, lalu unggah file rekaman suara.": "Pilih matéri, tuluy unggah file rekaman sora.",
    "MP3, WAV, M4A, atau WEBM. Maksimum 10 MB.": "MP3, WAV, M4A, atanapi WEBM. Panggedéna 10 MB.",
    "MP3, WAV, OGG, M4A, atau WEBM. Maksimum 10 MB.": "MP3, WAV, OGG, M4A, atanapi WEBM. Panggedéna 10 MB.",
    "Sedang merekam": "Nuju ngarékam",
    "Rekaman siap": "Rekaman parantos siap",
    "Rekam pelafalan": "Rékam lafal",
    "Tekan tombol rekam, ucapkan materi dengan jelas, lalu hentikan rekaman.": "Pencét tombol rékam, ucapkeun matéri kalayan écés, tuluy eureunkeun rékamanna.",
    "Menghubungkan mikrofon...": "Nuju nyambungkeun mikropon...",
    "Hentikan rekaman": "Eureunkeun rékaman",
    "Rekam ulang": "Rékam deui",
    "Mulai rekam": "Mimitian ngarékam",
    "Browser ini belum mendukung perekaman audio. Silakan unggah berkas dari folder.": "Panyungsi ieu teu acan ngadukung rékaman audio. Mangga unggah berkas tina polder.",
    "Rekaman gagal. Periksa mikrofon lalu coba lagi.": "Rékaman gagal. Pariksa mikropon teras cobian deui.",
    "Ukuran rekaman melebihi batas 10 MB. Silakan rekam ulang dengan durasi lebih singkat.": "Ukuran rékaman ngaleuwihan 10 MB. Mangga rékam deui kalayan durasi langkung pondok.",
    "Ukuran audio melebihi batas 10 MB.": "Ukuran audio ngaleuwihan wates 10 MB.",
    "Mikrofon tidak dapat diakses. Izinkan akses mikrofon atau unggah berkas dari folder.": "Mikropon teu tiasa diaksés. Idinan aksés mikropon atanapi unggah berkas tina polder.",
    "Audio tidak dapat disimpan. Periksa format dan ukuran berkas.": "Audio teu tiasa disimpen. Pariksa format sareng ukuran berkas.",
    "audio": "audio",
    "materi": "matéri",
    "Materi tanpa audio": "Matéri tanpa audio",
    "Pilih berkas rekaman suara untuk materi ini. Pelajar akan memutarnya saat belajar.": "Pilih berkas rekaman sora pikeun matéri ieu. Murid tiasa ngadangukeunana nalika diajar.",
    "Simpan audio": "Simpen audio",
    "Audio berhasil disimpan.": "Audio parantos hasil disimpen.",
    "Blok materi tanpa audio": "Blok matéri tanpa audio",
    "Pilih blok materi untuk mengunggah audio pelafalan.": "Pilih blok matéri pikeun unggah audio lafal.",
    "Semua materi sudah memiliki audio": "Sadaya matéri parantos gaduh audio.",
    "Belum ada blok materi lain yang perlu ditambahkan audio.": "Teu aya deui blok matéri nu peryogi ditambahan audio.",
    "Materi tanpa audio tidak ditemukan": "Teu kapendak matéri tanpa audio.",
    "Gunakan tab Tambah audio untuk memilih materi yang akan diberi audio.": "Anggo tab Tambah audio pikeun milih matéri nu badé dipasihan audio.",
    "Audio tidak tersedia.": "Audio teu sayogi.",
    "Kelola materi": "Atur matéri",
    "Aktivitas pelajar": "Kagiatan murid",
    "Jumlah pelajaran yang dituntaskan dan percobaan latihan dari data akun.": "Jumlah pangajaran nu diréngsékeun sareng usaha latihan tina data akun.",
    "Percobaan latihan": "Usaha latihan",
    "Cari konten": "Téangan eusi",
    "EDITOR PELAJARAN": "ÉDITOR PANGAJARAN",
    "Ubah pelajaran": "Robih pangajaran",
    "Susun teks dan contoh sesuai urutan belajar.": "Susun téks sareng conto nurutkeun runtuyan diajar.",
    "Blok materi": "Blok matéri",
    "Konteks:": "Kontéks:",
    "Audio tersedia": "Audio sayogi",
    "Tambah materi": "Tambah matéri",
    "Soal dinilai menggunakan kunci jawaban admin.": "Patalékan dipeunteun nganggo konci jawaban pangurus.",
    "Tambah latihan": "Tambah latihan",
    "Pelajaran tujuan": "Pangajaran tujuan",
    "Buat pelajaran terlebih dahulu sebelum menambahkan latihan.": "Jieun pangajaran heula sateuacan nambihan latihan.",
    "Pilih pelajaran untuk latihan ini, lalu tambahkan soal dan kunci jawaban.": "Pilih pangajaran pikeun latihan ieu, teras tambahkeun soal sareng konci jawaban.",
    Batal: "Bolay",
    Hapus: "Pupus",
    "Konten ini beserta semua bagian di dalamnya akan dihapus secara permanen.": "Eusi ieu sareng sadaya bagian di jerona bakal dipupus salamina.",
    "Menghapus...": "Nuju mupus...",
    "Ya, hapus": "Muhun, pupus",
    "Konten berhasil dihapus.": "Eusi parantos dipupus.",
    "Pilih opsi": "Pilih pilihan",
    "Menyimpan...": "Nuju nyimpen...",
    "Simpan perubahan": "Simpen parobahan",
    "Perubahan berhasil disimpan.": "Parobahan parantos disimpen.",
    Draf: "Draf",
    Ditinjau: "Ditinjau",
    Terbit: "Medal",
    Diarsipkan: "Diarsipkeun",
    Penjelasan: "Panjelasan",
    Kosakata: "Kekecapan",
    Dialog: "Paguneman",
    "Pilihan ganda": "Pilihan ganda",
    Mencocokkan: "Nyocogkeun",
    "Melengkapi teks": "Ngalengkepan téks",
    "Susun urutan": "Susun runtuyan",
    "Pilih aksara": "Pilih aksara",
    "Jenis soal menentukan kolom yang tampil dan format jawaban.": "Jinis patalékan nangtukeun kolom anu dipintonkeun jeung wangun jawaban.",
    "Tuliskan pertanyaan yang memiliki satu jawaban paling tepat.": "Tulis patalékan anu ngan boga hiji jawaban pangbenerna.",
    "Jelaskan pasangan yang harus dicari pelajar.": "Jelaskeun pasangan anu kedah dipilarian ku murid.",
    "Tulis kalimat dengan bagian kosong, gunakan ___ sebagai penanda.": "Tulis kalimah anu aya bagian kosongna, anggo ___ minangka tanda.",
    "Jelaskan bagian apa yang perlu disusun dan hasil urutannya.": "Jelaskeun bagian anu kedah disusun jeung runtuyan hasilna.",
    "Minta pelajar mengetik atau menyusun jawaban dalam Aksara Sunda.": "Pénta murid ngetik atanapi nyusun jawaban dina Aksara Sunda.",
    "Pilihan jawaban (satu per baris)": "Pilihan jawaban (hiji unggal jajar)",
    "Isi minimal dua pilihan, satu per baris. Jawaban benar harus sama persis dengan salah satunya.": "Eusian sahenteuna dua pilihan, hiji unggal jajar. Jawaban leres kedah sarua jeung salah sahijina.",
    "Pilihan pasangan (satu per baris)": "Pilihan pasangan (hiji unggal jajar)",
    "Isi satu pasangan per baris. Jawaban benar harus sama persis dengan salah satu baris.": "Eusian hiji pasangan unggal jajar. Jawaban leres kedah sarua jeung salah sahiji jajar.",
    "Bagian yang disusun (satu per baris)": "Bagian anu disusun (hiji unggal jajar)",
    "Isi satu kata atau potongan per baris. Urutan baris boleh diacak.": "Eusian hiji kecap atanapi bagian unggal jajar. Runtuyan jajar tiasa diacak.",
    "Isi dengan teks salah satu pilihan secara persis. Contoh: Permisi.": "Eusian ku téks salah sahiji pilihan kalawan sarua persis. Conto: Mangga.",
    "Isi dengan satu pilihan pasangan secara persis, termasuk tanda pemisahnya.": "Eusian ku hiji pilihan pasangan kalawan sarua persis, kaasup tanda pamisahna.",
    "Isi hanya bagian yang menggantikan tanda ___ pada soal.": "Eusian ngan bagian anu ngagantikeun tanda ___ dina soal.",
    "Tuliskan bagian-bagian dalam urutan benar, pisahkan dengan spasi.": "Tulis bagian-bagian dina runtuyan anu leres, pisahkeun ku spasi.",
    "Isi karakter Aksara Sunda yang benar. Contoh: ᮊ untuk bunyi ka.": "Eusian karakter Aksara Sunda anu leres. Conto: ᮊ pikeun sora ka.",
    "Jelaskan alasan jawaban benar dan arti pilihan yang ditanyakan.": "Jelaskeun sabab jawabanana leres jeung harti pilihan anu ditaroskeun.",
    "Jelaskan hubungan antara pasangan yang benar.": "Jelaskeun patalina antara pasangan anu leres.",
    "Terangkan mengapa kata tersebut melengkapi kalimat.": "Jelaskeun naha kecap éta ngalengkepan kalimah.",
    "Jelaskan susunan yang benar dan makna hasilnya.": "Jelaskeun runtuyan anu leres jeung harti hasilna.",
    "Sebutkan bunyi Latin atau petunjuk bentuk aksaranya.": "Sebutkeun sora Latin atanapi pituduh wangun aksarana.",
    "Angka kecil tampil lebih dulu. Contoh: 0 untuk soal pertama.": "Angka leutik dipintonkeun ti heula. Conto: 0 pikeun patalékan kahiji.",
    "Buat kuis": "Jieun kuis",
    "Isi informasi kuis, lalu tambahkan soal dan pilih jawaban benar dengan radio.": "Eusian inpormasi kuis, tuluy tambahkeun patalékan sareng pilih jawaban leres ku tombol radio.",
    "Informasi kuis": "Inpormasi kuis",
    "Pilih kelas dan materi yang akan menjadi sumber evaluasi.": "Pilih kelas sareng matéri anu bakal dijadikeun sumber évaluasi.",
    "Judul kuis": "Judul kuis",
    "Contoh: Kuis kosakata sapaan": "Conto: Kuis kekecapan salam",
    "Mata pelajaran": "Mata pangajaran",
    "Pilih mata pelajaran": "Pilih mata pangajaran",
    "Kelas / unit": "Kelas / unit",
    "Pilih kelas / unit": "Pilih kelas / unit",
    "Durasi (menit)": "Lilana (menit)",
    "Contoh: 30 menit untuk kuis singkat.": "Conto: 30 menit kanggo kuis singget.",
    "Nilai minimum lulus (%)": "Peunteun minimum lulus (%)",
    "Contoh: 70 berarti pelajar perlu menjawab benar minimal 70%.": "Conto: 70 hartina murid kedah ngajawab leres sahenteuna 70%.",
    "Batas percobaan (opsional)": "Wates nyobaan (opsional)",
    "Kosongkan agar bebas mengulang": "Kosongkeun sangkan tiasa diulang sabisana",
    "Contoh: 3 kali. Kosongkan agar pelajar bebas mengulang.": "Conto: 3 kali. Kosongkeun sangkan murid tiasa ngulang sabisana.",
    "Tulis pertanyaan, isi empat pilihan, lalu pilih radio pada jawaban yang benar.": "Tulis patalékan, eusian opat pilihan, tuluy pilih radio dina jawaban anu leres.",
    Pertanyaan: "Patalékan",
    "Pilihan jawaban": "Pilihan jawaban",
    "Pilih radio button untuk menandai jawaban yang benar": "Pilih tombol radio pikeun nandaan jawaban anu leres",
    "Tandai pilihan": "Tandaan pilihan",
    "sebagai jawaban benar": "minangka jawaban leres",
    Pilihan: "Pilihan",
    "Pembahasan untuk pelajar": "Panjelasan kanggo murid",
    "Contoh: ‘Punten’ dipakai saat meminta izin dengan sopan.": "Conto: ‘Punten’ dianggo nalika ménta idin kalayan sopan.",
    "Kuis dan soal berhasil disimpan.": "Kuis sareng patalékan hasil disimpen.",
    "Simpan kuis": "Simpen kuis",
    "Tambahkan pelajaran terlebih dahulu sebelum membuat kuis.": "Tambahkeun pangajaran heula sateuacan nyieun kuis.",
    "Latihan & kuis yang tersusun": "Latihan & kuis anu parantos disusun",
    "Kelola latihan dan kuis evaluasi untuk setiap pelajaran.": "Atur latihan sareng kuis évaluasi pikeun unggal pangajaran.",
    aktivitas: "kagiatan",
    "Aktivitas tidak ditemukan": "Kagiatan teu kapanggih",
    "Belum ada latihan atau kuis": "Teu acan aya latihan atanapi kuis",
    "Tambahkan pelajaran terlebih dahulu untuk membuat latihan atau kuis.": "Tambahkeun pangajaran heula pikeun nyieun latihan atanapi kuis.",
    "Gunakan Tambah latihan untuk membuat latihan, atau Buat kuis untuk menyusun evaluasi beserta soalnya.": "Anggo Tambah latihan pikeun nyieun latihan, atanapi Jieun kuis pikeun nyusun évaluasi sareng patalékanana.",
    "Tambah soal kuis": "Tambah patalékan kuis",
    "Ubah soal kuis": "Robih patalékan kuis",
    "Tambah soal latihan": "Tambah patalékan latihan",
    "Ubah soal latihan": "Robih patalékan latihan",
    "Pilih format soal dan lengkapi pilihan serta kunci jawabannya.": "Pilih wangun patalékan, tuluy lengkepan pilihan sareng konci jawabanana.",
    "Soal latihan untuk": "Patalékan latihan pikeun",
    "Pilih format soal; kolom akan menyesuaikan dengan jenis yang dipilih.": "Pilih wangun patalékan; kolom bakal saluyu sareng jinis anu dipilih.",
    "Pilih satu radio sebagai kunci jawaban. Pelajar akan menerima pembahasan setelah mengerjakan kuis.": "Pilih hiji radio minangka konci jawaban. Murid bakal nampi panjelasan saatos ngerjakeun kuis.",
    Durasi: "Lilana",
    menit: "menit",
    "Simpan soal": "Simpen patalékan",
    "Soal kuis berhasil diperbarui.": "Patalékan kuis hasil diropéa.",
    "Soal kuis berhasil ditambahkan.": "Patalékan kuis hasil ditambahkeun.",
    Judul: "Judul",
    "Urutan tampil": "Runtuyan tampilan",
    "Angka yang lebih kecil tampil lebih dulu.": "Angka nu leuwih leutik dipidangkeun heula.",
    "Status konten": "Status eusi",
    "Jenis blok": "Jinis blok",
    "Judul blok": "Judul blok",
    "Isi materi": "Eusi matéri",
    "Tulisan Latin": "Tulisan Latin",
    "Aksara Sunda (Unicode)": "Aksara Sunda (Unicode)",
    "Arti Bahasa Indonesia": "Harti dina Basa Indonésia",
    "Ragam wilayah": "Ragam wewengkon",
    "Tingkat tutur": "Undak usuk basa",
    "Konteks pemakaian": "Kontéks pamakéan",
    "MP3, WAV, OGG, atau M4A. Maksimum 10 MB.": "MP3, WAV, OGG, atanapi M4A. Panggedéna 10 MB.",
    "Jenis soal": "Jinis patalékan",
    "Instruksi soal": "Pituduh patalékan",
    "Pilihan / bagian (satu per baris)": "Pilihan / bagian (hiji per padalisan)",
    "Jawaban benar": "Jawaban leres",
    "Penjelasan untuk pelajar": "Panjelasan kanggo murid",
    "Nama kelas": "Nami kelas",
    "Deskripsi singkat": "Pedaran singget",
    "Tujuan unit": "Tujuan unit",
    "Ringkasan pelajaran": "Ringkesan pangajaran",
    "Nama latihan": "Nami latihan",
    "Ringkasan pengelolaan": "Ringkesan pangaturan",
    "Kelas & pelajaran": "Kelas & pangajaran",
    "Kosakata & konteks": "Kekecapan & kontéks",
    "Latihan & soal": "Latihan & patalékan",
    "Audio & media": "Audio & média",
    "Pelajar & progres": "Murid & kamajuan",
    "Lihat apa yang perlu disiapkan sebelum pelajar mulai belajar.": "Tingali naon waé nu kedah disiapkeun sateuacan murid ngamimitian diajar.",
    "Susun unit, tulis materi, dan terbitkan pelajaran.": "Susun unit, tulis matéri, sareng pedalkeun pangajaran.",
    "Tinjau kosakata, aksara, dan ragam pemakaian dalam materi.": "Tinjau kekecapan, aksara, sareng ragam pamakéan dina matéri.",
    "Kelola latihan dan kunci jawaban untuk setiap pelajaran.": "Atur latihan sareng konci jawaban unggal pangajaran.",
    "Kelola audio pelafalan yang terhubung dengan materi.": "Atur audio lafal nu nyambung kana matéri.",
    "Lihat aktivitas belajar untuk mengevaluasi materi.": "Tingali kagiatan diajar pikeun meunteun matéri.",
    "Ubah kelas belajar": "Robih kelas diajar",
    "Buat kelas belajar": "Jieun kelas diajar",
    "Perbarui informasi dan status kelas belajar.": "Robih inpormasi sareng status kelas diajar.",
    "Kelas baru disimpan sebagai draf. Setelah itu, tambahkan unit dan pelajaran sebelum menerbitkannya.":
        "Kelas énggal disimpen salaku draf. Teras tambihkeun unit sareng pangajaran sateuacan dipedalkeun.",
    "Kelas berhasil diperbarui.": "Kelas parantos dirobih.",
    "Kelas baru berhasil dibuat.": "Kelas énggal parantos dijieun.",
    "Unit pada kelas": "Unit dina kelas",
    "Susun tujuan dan urutan belajar.": "Susun tujuan sareng runtuyan diajar.",
    "Pelajaran pada unit": "Pangajaran dina unit",
    "Soal untuk": "Patalékan kanggo",
    "Pelajar akan melihat penjelasan setelah mengirim jawaban.": "Murid bakal ningali panjelasan saatos ngirim jawaban.",
    "Ubah blok materi": "Robih blok matéri",
    "Tambah blok materi": "Tambah blok matéri",
    "Teks, kosakata, aksara, konteks pemakaian, dan audio dalam satu blok.": "Téks, kekecapan, aksara, kontéks pamakéan, sareng audio dina hiji blok.",
    "Ubah latihan": "Robih latihan",
    "Beri judul latihan sebelum menambahkan soal dan kunci jawaban.": "Pasihan judul latihan sateuacan nambihan patalékan sareng konci jawaban.",
    "Ubah soal": "Robih patalékan",
    "Belum ada kelas belajar": "Teu acan aya kelas diajar",
    "Buat kelas untuk mulai mengatur unit dan pelajaran.": "Jieun kelas kanggo ngamimitian ngatur unit sareng pangajaran.",
    "Pilih kelas belajar": "Pilih kelas diajar",
    "Cari kelas...": "Téangan kelas...",
    "Belum ada unit": "Teu acan aya unit",
    "Tambahkan unit untuk mulai menyusun urutan belajar.": "Tambihkeun unit kanggo ngamimitian nyusun runtuyan diajar.",
    "Belum ada pelajaran": "Teu acan aya pangajaran",
    "Buat pelajaran pertama untuk unit ini.": "Jieun pangajaran munggaran kanggo unit ieu.",
    "Kelas tidak ditemukan": "Kelas teu kapanggih",
    "Ubah pencarian atau filter status untuk melihat kelas lain.": "Robih pamilarian atanapi saringan status kanggo ningali kelas sanés.",
    "Buat kelas pertama Anda untuk memulai.": "Jieun kelas munggaran anjeun kanggo ngamimitian.",
    "Belum ada ringkasan pelajaran.": "Teu acan aya ringkesan pangajaran.",
    "Ubah entri": "Robih éntri",
    "Ubah blok audio": "Robih blok audio",
    "Hapus blok": "Pupus blok",
    "Hapus latihan": "Pupus latihan",
    "Hapus soal": "Pupus patalékan",
    "Cari kata, arti, aksara, atau ragam...": "Téangan kecap, harti, aksara, atanapi ragam...",
    "Tidak ada entri yang cocok": "Teu aya éntri nu cocog",
    "Belum ada kosakata atau aksara": "Teu acan aya kekecapan atanapi aksara",
    "Coba istilah pencarian lain.": "Coba istilah pamilarian sanés.",
    "Tambahkan blok kosakata atau aksara pada pelajaran untuk melihatnya di sini.": "Tambihkeun blok kekecapan atanapi aksara dina pangajaran kanggo ningalina di dieu.",
    "Cari judul latihan atau pelajaran...": "Téangan judul latihan atanapi pangajaran...",
    "Latihan tidak ditemukan": "Latihan teu kapanggih",
    "Belum ada latihan": "Teu acan aya latihan",
    "Buka pelajaran dalam kelas belajar, lalu tambahkan latihan dan soal.": "Buka pangajaran dina kelas diajar, teras tambihkeun latihan sareng patalékan.",
    "Cari audio berdasarkan kata atau pelajaran...": "Téangan audio dumasar kecap atanapi pangajaran...",
    "Audio tidak ditemukan": "Audio teu kapanggih",
    "Belum ada audio": "Teu acan aya audio",
    "Coba pencarian lain.": "Coba pamilarian sanés.",
    "Unggah pelafalan pada blok materi agar dapat didengarkan pelajar.": "Unggah lafal kana blok matéri sangkan tiasa didangu ku murid.",
    "Cari nama atau email pelajar...": "Téangan nami atanapi email murid...",
    "Pelajar tidak ditemukan": "Murid teu kapanggih",
    "Belum ada pelajar": "Teu acan aya murid",
    "Coba nama atau email lain.": "Coba nami atanapi email sanés.",
    "Aktivitas akan terlihat setelah akun pelajar terdaftar dan mulai belajar.": "Kagiatan bakal katingali saatos akun murid kadaptar sareng ngamimitian diajar.",
    "Isi pelajaran": "Eusi pangajaran",
    "Materi belum diisi": "Matéri teu acan dieusi",
    "Pelajaran memerlukan paling sedikit satu blok materi sebelum bisa diterbitkan.": "Pangajaran peryogi sahenteuna hiji blok matéri sateuacan tiasa dipedalkeun.",
    "Tambahkan latihan, lalu tulis soal, jawaban, dan penjelasannya.": "Tambihkeun latihan, teras tulis patalékan, jawaban, sareng panjelasanana.",
    "RUANG BELAJAR": "ROHANGAN DIAJAR",
    "Dasbor belajar": "Dasbor diajar",
    "Sedikit demi sedikit, makin mahir berbahasa Sunda.": "Saeutik-saeutik, beuki mahér nyarios Basa Sunda.",
    "Mulai perjalanan belajarmu hari ini.": "Mimitian lalampahan diajar anjeun dinten ieu.",
    Lanjutkan: "Teruskeun",
    "dan temukan hal baru di setiap pelajaran.": "sareng panggihan hal énggal dina unggal pangajaran.",
    "Pilih kelas Bahasa Sunda atau Aksara Sunda untuk membuka pelajaran pertama.": "Pilih kelas Basa Sunda atanapi Aksara Sunda kanggo muka pangajaran munggaran.",
    "Lanjutkan belajar": "Teruskeun diajar",
    "Lihat kelas belajar": "Tingali kelas diajar",
    "Belajar Bahasa dan Aksara Sunda": "Diajar Basa sareng Aksara Sunda",
    "Ruang saya": "Rohangan abdi",
    Masuk: "Lebet",
    "Buka ruang kelola": "Buka rohangan pangaturan",
    "Lanjut belajar": "Teruskeun diajar",
    "Mulai belajar": "Mimitian diajar",
    "Navigasi utama": "Navigasi utama",
    "Buka menu navigasi": "Buka ménu navigasi",
    "Tutup menu navigasi": "Tutup ménu navigasi",
    "Cara belajar": "Cara diajar",
    "Daftar gratis": "Daptar gratis",
    "Mulai belajar gratis": "Mimitian diajar gratis",
    "Jelajahi cara belajar": "Jajah cara diajar",
    "Ruang belajar Bahasa dan Aksara Sunda": "Rohangan diajar Basa sareng Aksara Sunda",
    "Pilih fitur untuk melihat pratinjau": "Pilih fitur kanggo ningali sawangan",
    "Kelas Bahasa Sunda": "Kelas Basa Sunda",
    "Mulai dari sapaan, kosakata, sampai ragam tutur dalam konteksnya.": "Mimitian tina salam, kekecapan, dugi ka ragam basa sareng kontéksna.",
    "Pelajari karakter, rarangkén, membaca, dan menulis secara bertahap.": "Diajar karakter, rarangkén, maca, sareng nyerat sacara runtuy.",
    "Latihan setelah belajar": "Latihan saatos diajar",
    "Coba soal singkat dan lihat penjelasan untuk menguatkan pemahaman.": "Cobi patalékan pondok sareng tingali panjelasan kanggo nguatkeun pamahaman.",
    "Tanya Tutor AI": "Taroskeun ka Tutor AI",
    "Diskusikan materi dan lihat rujukan pelajaran yang digunakan.": "Sawalakeun matéri sareng tingali rujukan pangajaran anu dianggo.",
    "Lihat detail": "Tingali wincikan",
    "Putar pelafalan": "Puter lafal",
    "Klik ungkapan untuk mendengarkan pelafalan": "Klik ungkara kanggo ngadangukeun lafalna",
    "Sedang diputar": "Nuju diputer",
    "Browser ini belum mendukung suara.": "Panyungsi ieu teu acan ngadukung sora.",
    "Suara tidak dapat diputar di perangkat ini.": "Sora teu tiasa diputer dina alat ieu.",
    "Suara pelafalan": "Sora lafal",
    "Pilihan suara bergantung pada dukungan Bahasa Sunda atau Indonesia di perangkat.": "Pilihan sora gumantung kana pangrojong Basa Sunda atanapi Basa Indonésia dina alat.",
    Permisi: "Punten",
    "Terima kasih": "Hatur nuhun",
    "Apa bedanya kata “abdi” dan “urang”?": "Naon bédana kecap “abdi” sareng “urang”?",
    "Keduanya berarti “saya”, tetapi penggunaannya bergantung pada konteks.": "Duanana hartina “abdi”, tapi pamakéanana gumantung kana kontéks.",
    "Pelajari Bahasa Sunda dan Aksara Sunda lewat materi terarah, latihan interaktif, dan Tutor AI dengan rujukan pelajaran.":
        "Diajar Basa Sunda sareng Aksara Sunda ngaliwatan matéri anu runtuy, latihan interaktif, sareng Tutor AI kalayan rujukan pangajaran.",
    "Tepat! Wilujeng enjing berarti selamat pagi.": "Leres! Wilujeng enjing hartina wilujeng enjing.",
    "Coba lagi, wilujeng enjing adalah sapaan pagi.": "Cobi deui, wilujeng enjing téh salam isuk-isuk.",
    "Coba susun aksara": "Cobi susun aksara",
    "Susun “Basa” dari dua karakter berikut.": "Susun “Basa” tina dua karakter ieu.",
    "Ulangi latihan": "Balikan deui latihan",
    Jawabanmu: "Jawaban anjeun",
    "Palet aksara Sunda": "Palét Aksara Sunda",
    "Hapus karakter": "Pupus karakter",
    "Leres! Anjeun nyusun Basa kalayan leres.": "Leres! Anjeun nyusun Basa kalayan leres.",
    "Can leres. Cobi deui susun aksarana.": "Can leres. Cobi deui susun aksarana.",
    "Benar! Kamu berhasil menyusun Basa Sunda.": "Leres! Anjeun parantos tiasa nyusun Basa Sunda.",
    "Belum tepat. Coba susun aksaranya lagi.": "Teu acan leres. Cobi susun deui aksarana.",
    "Pilih karakter untuk mengisi jawaban.": "Pilih karakter kanggo ngeusian jawaban.",
    "Periksa jawaban": "Pariksa jawaban",
    "Belajar Sunda, satu langkah kecil setiap hari.": "Diajar Sunda, saeutik-saeutik unggal dinten.",
    "Pahami ungkapan sehari-hari, kenali Aksara Sunda, lalu latih kemampuanmu lewat materi yang tersusun dan progres yang tersimpan.":
        "Pahami ungkara sapopoé, wawanohan kana Aksara Sunda, teras latihan ngaliwatan matéri anu disusun tur kamajuan anu disimpen.",
    "Kosakata, ungkapan, dan konteks.": "Kekecapan, ungkara, sareng kontéks.",
    "Baca dan susun karakter Sunda.": "Baca sareng susun karakter Sunda.",
    "Latihan bertahap": "Latihan sacara runtuy",
    "Cek pemahaman setelah belajar.": "Pariksa pamahaman saatos diajar.",
    "Tanya materi dengan rujukan.": "Taroskeun matéri sareng rujukan.",
    "Contoh materi": "Conto matéri",
    "Sapaan dan ungkapan": "Salam sareng ungkara",
    "3 kosakata": "3 kekecapan",
    "Gunakan kata yang tepat, di situasi yang tepat.": "Anggo kecap anu merenah dina kaayaan anu pas.",
    "Pelajari arti, pelafalan, ragam tutur, dan konteks pemakaian melalui unit yang teratur. Setiap pelajaran menggabungkan penjelasan dan contoh yang bisa langsung dicoba.":
        "Diajar harti, lafal, ragam basa, sareng kontéks pamakéan ngaliwatan unit anu runtuy. Unggal pangajaran ngagabungkeun panjelasan sareng conto anu tiasa langsung dicobian.",
    "Ungkapan yang dekat dengan percakapan sehari-hari": "Ungkara anu raket sareng paguneman sapopoé",
    "Contoh pemakaian beserta artinya": "Conto pamakéan sareng hartina",
    "Audio saat tersedia pada materi": "Audio upami sayogi dina matéri",
    "Lihat kelas Bahasa Sunda": "Tingali kelas Basa Sunda",
    "Kenali bentuknya. Baca bunyinya. Coba menulisnya.": "Wawanohan kana wangunna. Baca sorana. Cobi tuliskeun.",
    "Aksara Sunda punya jalur materi dan latihan tersendiri. Pelajari karakter dan rarangkén secara bertahap, lalu susun jawaban dengan palet aksara di layar.":
        "Aksara Sunda gaduh matéri sareng latihan anu misah. Diajar karakter sareng rarangkén sacara runtuy, teras susun jawaban nganggo palét aksara dina layar.",
    "Mengenal karakter": "Wawanohan kana karakter",
    "Latihan membaca": "Latihan maca",
    "Latihan menulis": "Latihan nyerat",
    "Jelajahi kelas Aksara Sunda": "Jajah kelas Aksara Sunda",
    "Kenali aksara": "Wawanohan kana aksara",
    "Aksara swara": "Aksara swara",
    "Pratinjau materi": "Sawangan matéri",
    "dan lainnya": "sareng nu sanésna",
    "Belajar dengan bantuan AI": "Diajar dibantuan ku AI",
    "Punya pertanyaan? Mulai dari materi yang sedang kamu pelajari.": "Aya patalékan? Mimitian tina matéri anu keur dipalajari.",
    "Tutor AI membantu menjelaskan materi, melatih percakapan teks, dan memberi saran tulisan. Jawaban menyertakan rujukan materi agar kamu bisa memeriksa kembali konteksnya.":
        "Tutor AI ngabantosan ngajelaskeun matéri, latihan paguneman téks, sareng masihan saran tulisan. Jawaban dibarengan ku rujukan matéri supados kontéksna tiasa dipariksa deui.",
    "Jawaban AI dapat keliru. Gunakan materi dan rujukan sebagai panduan belajar.": "Jawaban AI tiasa lepat. Anggo matéri sareng rujukan minangka pituduh diajar.",
    "Tutor AI Bahasa Sunda": "Tutor AI Basa Sunda",
    "Belajar dari materi yang diterbitkan": "Diajar tina matéri anu parantos dipedalkeun",
    "Kapan saya memakai kata punten?": "Iraha abdi nganggo kecap punten?",
    "Punten dapat digunakan saat meminta izin atau memulai percakapan dengan sopan.": "Punten tiasa dianggo nalika nyuhunkeun widi atanapi ngamimitian paguneman kalayan sopan.",
    "Rujukan pelajaran": "Rujukan pangajaran",
    "Sapaan dan ungkapan · Bahasa Sunda": "Salam sareng ungkara · Basa Sunda",
    "Belajar terarah, progres tetap tercatat.": "Diajar kalayan puguh, kamajuan tetep kacatet.",
    "Mulai dari topik dasar lalu lanjutkan sesuai ritmemu. Sawala menyimpan pelajaran dan hasil latihan di akunmu.":
        "Mimitian tina jejer dasar teraskeun nurutkeun wirahma sorangan. Sawala nyimpen pangajaran sareng hasil latihan dina akun anjeun.",
    "Pilih kelas": "Pilih kelas",
    "Bahasa Sunda atau Aksara Sunda.": "Basa Sunda atanapi Aksara Sunda.",
    "Ikuti pelajaran": "Turutan pangajaran",
    "Materi ditata dalam unit yang runtut.": "Matéri disusun dina unit anu runtuy.",
    "Coba latihan": "Cobi latihan",
    "Periksa pemahaman dan baca penjelasan.": "Pariksa pamahaman sareng baca panjelasan.",
    "Lihat progres": "Tingali kamajuan",
    "Kembali ke pelajaran yang terakhir dibuka.": "Balik kana pangajaran anu pamungkas dibuka.",
    "Mulai dari satu pelajaran": "Mimitian tina hiji pangajaran",
    "Sedikit demi sedikit, kamu akan semakin akrab dengan Sunda.": "Saeutik-saeutik, anjeun bakal beuki wawuh kana Basa Sunda.",
    "Buat akun untuk menyimpan progres dan melanjutkan kapan saja.": "Jieun akun kanggo nyimpen kamajuan sareng neraskeun iraha waé.",
    "Buat akun gratis": "Jieun akun gratis",
    "Ruang belajar Bahasa Sunda dan Aksara Sunda yang tertata untuk pelajar.": "Rohangan diajar Basa Sunda sareng Aksara Sunda anu disusun kanggo murid.",
    Jelajahi: "Jajah",
    "Fitur belajar": "Fitur diajar",
    Akun: "Akun",
    "Materi dan kosakata": "Matéri sareng kekecapan",
    "Latihan aksara": "Latihan aksara",
    "Latihan kosakata": "Latihan kekecapan",
    "Apa arti “wilujeng enjing”?": "Naon hartina “wilujeng enjing”?",
    "Selamat pagi": "Wilujeng enjing",
    "Selamat malam": "Wilujeng wengi",
    "Rujukan dari materi belajar": "Rujukan tina matéri diajar",
    "Wilujeng sumping,": "Wilujeng sumping,",
    "Lanjutkan langkah belajar Bahasa dan Aksara Sunda hari ini.": "Teruskeun diajar Basa sareng Aksara Sunda dinten ieu.",
    "Lihat progres saya": "Tingali kamajuan abdi",
    "BELAJAR SESUAI LANGKAHMU": "DIAJAR NURUTKEUN LÉNGKAH SORANGAN",
    "Progres keseluruhan": "Kamajuan sakabéhna",
    "KURIKULUM BELAJAR": "KURIKULUM DIAJAR",
    "LANGKAH BERIKUTNYA": "LÉNGKAH SALAJENGNA",
    "Pelajaran berikutnya": "Pangajaran salajengna",
    "Buka pelajaran yang belum selesai dari kelasmu.": "Buka pangajaran anu teu acan réngsé tina kelas anjeun.",
    "Semua pelajaran di kelas yang tersedia sudah selesai.": "Sadaya pangajaran dina kelas nu sayogi parantos réngsé.",
    "Pilih kelas belajarmu": "Pilih kelas diajar anjeun",
    "Bahasa & aksara terpisah": "Basa & aksara dipisah",
    "Kelas belajar belum tersedia.": "Kelas diajar teu acan sayogi.",
    "PELAJARAN TERAKHIR": "PANGAJARAN PANGANYARNA",
    "Buka pelajaran": "Buka pangajaran",
    "Belum ada pelajaran yang dibuka.": "Teu acan aya pangajaran nu dibuka.",
    "Butuh teman belajar?": "Peryogi rerencangan diajar?",
    "Tanyakan materi atau latih percakapan bersama Tutor AI.": "Taroskeun matéri atanapi latihan paguneman sareng Tutor AI.",
    "Buka Tutor AI": "Buka Tutor AI",
    "LATIHAN KHUSUS": "LATIHAN HUSUS",
    "Ruang Aksara Sunda": "Rohangan Aksara Sunda",
    "RUANG BELAJAR BAHASA & AKSARA": "ROHANGAN DIAJAR BASA & AKSARA",
    "Kenali Bahasa Sunda, satu pelajaran setiap kali.": "Wawanohan kana Basa Sunda, hiji pangajaran saban waktos.",
    "Dari kosakata yang dipakai sehari-hari sampai bentuk Aksara Sunda. Pilih kelas, pelajari materinya, lalu uji pemahaman dengan latihan.":
        "Ti kekecapan sapopoé dugi ka wangun Aksara Sunda. Pilih kelas, pelajari matérina, teras cobian latihan.",
    "Belajar mandiri, sesuai langkah Anda.": "Diajar mandiri, nurutkeun léngkah anjeun.",
    "Apa yang akan dipelajari?": "Naon nu badé dipelajari?",
    "BAHASA SUNDA": "BASA SUNDA",
    "Kata, ungkapan, dan konteks.": "Kecap, ungkara, sareng kontéks.",
    "Pelajari arti, cara mengucapkan, dan kapan sebuah ungkapan digunakan.": "Pelajari harti, cara ngucapkeun, sareng iraha hiji ungkara dianggo.",
    "Setiap materi disusun dalam kelas belajar": "Unggal matéri disusun dina kelas diajar",
    "Unit → Pelajaran → Latihan": "Unit → Pangajaran → Latihan",
    "AKSARA SUNDA": "AKSARA SUNDA",
    "Kenali, baca, lalu susun aksara.": "Wawanohan, baca, teras susun aksara.",
    "Belajar dengan arah yang jelas.": "Diajar kalayan arah nu écés.",
    "Dua kelas belajar terpisah membantu Anda memahami bahasa dan aksara sesuai urutannya. Progres tersimpan, sehingga Anda bisa kembali tepat ke pelajaran terakhir. Materi dibuka setelah ditinjau oleh pengelola.":
        "Dua kelas diajar nu dipisah ngabantosan anjeun ngartos basa sareng aksara sacara runtuy. Kamajuan disimpen sangkan tiasa neraskeun pangajaran pamungkas. Matéri dibuka saatos ditinjau ku pangurus.",
    "Bahasa dan aksara, dipelajari dengan cermat.": "Basa sareng aksara, dipelajari kalayan taliti.",
    "KELAS BELAJAR ·": "KELAS DIAJAR ·",
    "Kelas Belajar": "Kelas Diajar",
    KURIKULUM: "KURIKULUM",
    "Daftar unit & pelajaran": "Daptar unit & pangajaran",
    "Pelajari materi sesuai urutan atau buka topik yang ingin ditinjau.": "Pelajari matéri sacara runtuy atanapi buka jejer nu badé ditingali.",
    PELAJARAN: "PANGAJARAN",
    "Belum ada pelajaran terbit dalam unit ini.": "Teu acan aya pangajaran medal dina unit ieu.",
    "Materi sedang disiapkan": "Matéri nuju disiapkeun",
    "Unit akan muncul setelah diterbitkan oleh admin.": "Unit bakal muncul saatos dipedalkeun ku pangurus.",
    "PROGRES KELAS": "KAMAJUAN KELAS",
    "Lihat semua progres": "Tingali sadaya kamajuan",
    "Belajar lewat latihan": "Diajar ngaliwatan latihan",
    "Setiap pelajaran dapat memuat latihan untuk mencoba materi yang baru dibaca.": "Unggal pangajaran tiasa ngandung latihan pikeun nyobian matéri nu nembe dibaca.",
    "Ruang latihan aksara": "Rohangan latihan aksara",
    "KONTEKS PEMAKAIAN": "KONTÉKS PAMAKÉAN",
    KOSAKATA: "KEKECAPAN",
    Kosakata: "Kekecapan",
    "Kosakata dalam materi": "Kekecapan dina matéri",
    Arti: "Harti",
    "PENGANTAR MATERI": "BUBUKA MATÉRI",
    PENGANTAR: "BUBUKA",
    PENJELASAN: "PENJELASAN",
    DIALOG: "DIALOG",
    "Kata dalam Bahasa Sunda": "Kecap dina Basa Sunda",
    "Arti dalam Bahasa Indonesia": "Harti dina Basa Indonésia",
    "Bunyi yang dibaca": "Sora anu dibaca",
    "Bentuk Aksara Sunda": "Wangun Aksara Sunda",
    "Ragam tutur": "Ragam basa",
    "Ragam daerah": "Ragam wewengkon",
    "Kapan digunakan": "Iraha dianggo",
    "Contoh pemakaian": "Conto pamakéan",
    "Cara mempelajari bagian ini": "Cara diajar dina bagian ieu",
    "Penjelasan materi": "Panjelasan matéri",
    "Isi dialog": "Eusi dialog",
    "Maksud dialog": "Harti dialog",
    "Sumber audio": "Sumber audio",
    "Contoh pelafalan": "Conto lafal",
    "Dengarkan pelafalan": "Dangukeun lafal",
    "Ragam loma digunakan dalam percakapan akrab. Sesuaikan dengan hubungan dan situasi.": "Ragam loma dianggo dina paguneman akrab. Saluyukeun sareng hubungan sareng kaayaan.",
    "Ragam lemes digunakan untuk berbicara dengan sopan dan menghormati lawan bicara.": "Ragam lemes dianggo pikeun nyarios sopan sareng ngahormat ka lawan nyarios.",
    "Tingkat tutur dapat berubah sesuai lawan bicara dan situasi.": "Tingkat basa tiasa robih gumantung ka saha sareng dina kaayaan kumaha nyariosna.",
    "Cocokkan kata dengan artinya, lalu perhatikan contoh saat kata ini digunakan dalam kalimat.": "Cocogkeun kecap sareng hartina, teras tingali conto pamakéan kecap ieu dina kalimah.",
    Dengarkan: "Dengekeun",
    "Audio tidak dapat diputar di browser ini.": "Audio teu tiasa diputer dina panyungsi ieu.",
    "· PELAJARAN": "· PANGAJARAN",
    "Isi pelajaran belum tersedia.": "Eusi pangajaran teu acan sayogi.",
    "Uji pemahaman": "Cobian pamahaman",
    "Kerjakan latihan untuk melihat jawaban dan penjelasannya.": "Pigawé latihan pikeun ningali jawaban sareng panjelasanana.",
    "Kembali ke kelas": "Balik ka kelas",
    "Dalam pelajaran ini": "Dina pangajaran ieu",
    "bagian materi ·": "bagian matéri ·",
    "Selesai membaca?": "Parantos réngsé maca?",
    "Tandai pelajaran selesai agar progres belajar tersimpan.": "Tandaan pangajaran parantos réngsé sangkan kamajuan diajar disimpen.",
    "JEJAK BELAJAR": "LALAMPAHAN DIAJAR",
    "Progres belajar": "Kamajuan diajar",
    "Kembali ke pelajaran yang sudah dimulai dan tinjau hasil latihan Anda.": "Balik deui ka pangajaran nu parantos dimimitian sareng tingali hasil latihan anjeun.",
    "PELAJARAN SELESAI": "PANGAJARAN RÉNGSÉ",
    "SEDANG DIPELAJARI": "NUJU DIPALAJARI",
    "LATIHAN DIKERJAKAN": "LATIHAN DIPIGAWÉ",
    "Belum memulai pelajaran": "Teu acan ngamimitian pangajaran",
    "Pilih satu kelas belajar untuk membuka pelajaran pertama Anda.": "Pilih hiji kelas diajar pikeun muka pangajaran munggaran anjeun.",
    "Riwayat latihan": "Sajarah latihan",
    "jawaban benar": "jawaban leres",
    "Belum ada hasil latihan": "Teu acan aya hasil latihan",
    "Latihan akan muncul di sini setelah Anda mengerjakannya dari halaman pelajaran.": "Latihan bakal muncul di dieu saatos anjeun migawéna tina kaca pangajaran.",
    "Hasil latihan": "Hasil latihan",
    "JAWABAN BENAR": "JAWABAN LERES",
    "Baca penjelasan tiap soal sebelum mencoba lagi.": "Baca panjelasan unggal patalékan sateuacan nyobian deui.",
    "Tinjauan jawaban": "Tinjauan jawaban",
    "Jawaban Anda": "Jawaban anjeun",
    "Coba lagi": "Cobian deui",
    "RUANG LATIHAN": "ROHANGAN LATIHAN",
    "Latihan ini belum memiliki soal. Kembali ke pelajaran dan coba lagi nanti.": "Latihan ieu teu acan gaduh patalékan. Balik ka pangajaran sareng cobian deui engké.",
    "Ketuk bagian sesuai urutan. Gunakan Hapus urutan untuk memulai kembali.": "Toél bagian nurutkeun runtuyan. Anggo Pupus runtuyan kanggo ngamimitian deui.",
    "Hapus urutan": "Pupus runtuyan",
    "Palet aksara · pilih karakter atau gunakan papan ketik": "Palét aksara · pilih karakter atanapi anggo papan ketik",
    "Soal berikutnya": "Patalékan salajengna",
    Sebelumnya: "Saméméhna",
    "Progres latihan": "Kamajuan latihan",
    Petunjuk: "Pituduh",
    "Kembali ke pelajaran": "Balik ka pangajaran",
    Soal: "Patalékan",
    SOAL: "PATALÉKAN",
    soal: "patalékan",
    Pelajaran: "Pangajaran",
    pelajaran: "pangajaran",
    unit: "unit",
    dari: "tina",
    selesai: "réngsé",
    "Latihan Aksara": "Latihan Aksara",
    "Mengenal dan menulis Aksara Sunda": "Wawanohan sareng nyerat Aksara Sunda",
    "Pilih latihan dari materi yang tersedia. Kerjakan soal baca, susun, dan tulis aksara sesuai langkah belajar Anda.":
        "Pilih latihan tina matéri nu sayogi. Pigawé patalékan maca, nyusun, sareng nyerat aksara nurutkeun léngkah diajar anjeun.",
    "PILIH LATIHAN": "PILIH LATIHAN",
    "Semua latihan aksara": "Sadaya latihan aksara",
    "PERPUSTAKAAN MATERI": "PERPUSTAKAAN MATÉRI",
    "Cari materi belajar": "Téangan matéri diajar",
    Cari: "Téangan",
    "Belum ada materi yang cocok. Coba kata kunci lain atau buka": "Teu aya matéri nu cocog. Coba kecap konci sanés atanapi buka",
    "kelas belajar": "kelas diajar",
    "Tanyakan materi, berlatih percakapan, atau minta saran tulisan. Periksa kembali jawaban dengan rujukan pelajaran.":
        "Taroskeun matéri, latihan paguneman, atanapi nyuhunkeun saran tulisan. Pariksa deui jawaban ku rujukan pangajaran.",
    "MODE BALASAN": "MODE WAWALER",
    "Mode balasan": "Mode waleran",
    "Mode ini mengatur balasan pesan berikutnya. Riwayat tetap di percakapan yang sama.": "Mode ieu ngatur waleran pikeun talatah salajengna. Sajarahna tetep dina paguneman anu sami.",
    "Belajar dari materi": "Diajar tina matéri",
    "Rujukan pelajaran muncul bersama jawaban jika tersedia.": "Rujukan pangajaran muncul sareng jawaban upami sayogi.",
    "Lihat kelas": "Tingali kelas",
    "PERTANYAAN ANDA": "PATALÉKAN ANJEUN",
    "JAWABAN AI": "JAWABAN AI",
    "JAWABAN CONTOH": "JAWABAN CONTO",
    "Contoh riwayat": "Conto sajarah",
    "AI belum terhubung": "AI teu acan nyambung",
    "Tutor AI dinonaktifkan": "Tutor AI dipareuman",
    "Pertanyaan tetap mencari materi terbit, tetapi jawaban AI baru aktif setelah pengelola mengatur penyedia AI.":
        "Patalékan tetep milarian matéri anu parantos dipedalkeun. Jawaban AI bakal aktip saatos pangurus ngatur panyadia AI.",
    "Pertanyaan tetap mencari rujukan materi. Pengelola perlu mengaktifkan kembali Tutor AI untuk jawaban otomatis.":
        "Patalékan tetep milarian rujukan matéri. Pangurus kedah ngaktipkeun deui Tutor AI kanggo jawaban otomatis.",
    "Buka pengaturan Tutor AI": "Buka setélan Tutor AI",
    "Percakapan Tutor AI": "Paguneman Tutor AI",
    "Tanyakan arti, penggunaan, atau isi pelajaran Bahasa Sunda.": "Taroskeun harti, pamakéan, atanapi eusi pangajaran Basa Sunda.",
    "Berlatih bergiliran. Tutor mengingat percakapan sebelumnya dalam mode ini dan mengajukan pertanyaan lanjutan.": "Latihan silih gentian. Tutor nginget paguneman saméméhna dina mode ieu sareng neraskeun ku patalékan.",
    "Tempel kalimat Bahasa Sunda yang ingin diperiksa.": "Tempelkeun kalimah Basa Sunda anu badé dipariksa.",
    "Contoh: Naon hartina punten?": "Conto: Naon hartina punten?",
    "Contoh: Wilujeng enjing, kumaha damang?": "Conto: Wilujeng enjing, kumaha damang?",
    "Tulis kalimat Bahasa Sunda yang ingin ditinjau...": "Tulis kalimah Basa Sunda anu badé ditinjau...",
    "Gunakan Enter untuk mengirim, Shift+Enter untuk baris baru.": "Anggo Enter kanggo ngirim, Shift+Enter kanggo nambihan garis énggal.",
    "Cari rujukan materi": "Téangan rujukan matéri",
    pesan: "pesen",
    "Pesan belum terkirim. Coba lagi.": "Talatah teu acan kakirim. Cobi deui.",
    "Terjemahan Indo–Sunda": "Tarjamahan Indonésia–Sunda",
    "Terjemahkan kata atau kalimat Bahasa Indonesia ke Bahasa Sunda.": "Tarjamahkeun kecap atanapi kalimah Basa Indonésia kana Basa Sunda.",
    "Contoh: Terjemahkan ‘Saya ingin belajar’ ke Bahasa Sunda.": "Conto: Tarjamahkeun ‘Abdi hoyong diajar’ kana Basa Sunda.",
    "Menunggu balasan...": "Ngantosan waleran...",
    "Tutor sedang menyiapkan jawaban...": "Tutor nuju nyiapkeun waleran...",
    "Pesan sedang dikirim": "Talatah nuju dikirim",
    "Hapus percakapan": "Pupus paguneman",
    "Hapus seluruh riwayat percakapan?": "Pupus sadaya sajarah paguneman?",
    "Hapus riwayat Tutor AI?": "Pupus sajarah Tutor AI?",
    "Semua percakapan Tutor AI akan dihapus permanen dan tidak dapat dipulihkan.": "Sadaya paguneman Tutor AI bakal dipupus salamina sareng teu tiasa dipulangkeun deui.",
    "Hapus semua percakapan": "Pupus sadaya paguneman",
    "Rujukan materi:": "Rujukan matéri:",
    "Mulai percakapan baru": "Mimitian paguneman énggal",
    "Ajukan pertanyaan tentang materi yang sudah diterbitkan untuk mulai belajar bersama tutor.":
        "Ajukeun patalékan ngeunaan matéri nu parantos dipedalkeun kanggo ngamimitian diajar sareng tutor.",
    "Jenis bantuan": "Jinis pitulung",
    "Tanya jawab materi": "Patalékan matéri",
    "Latihan percakapan teks": "Latihan paguneman téks",
    "Saran tulisan": "Saran tulisan",
    "Pesan Anda": "Talatah anjeun",
    "Tutor AI dapat membuat kekeliruan. Tinjau rujukan pelajaran sebelum menerapkan jawaban.": "Tutor AI tiasa lepat. Tinjau rujukan pangajaran sateuacan ngalarapkeun jawaban.",
    "unit ·": "unit ·",
    "pelajaran ·": "pangajaran ·",
    "blok ·": "blok ·",
    "Materi (": "Matéri (",
    "Latihan (": "Latihan (",
    Latihan: "Latihan",
    "Buka kelas": "Buka kelas",
    LATIHAN: "LATIHAN",
    "soal ·": "patalékan ·",
    "Latihan aksara belum diterbitkan. Buka kelas Aksara Sunda untuk melihat materi yang sudah tersedia.":
        "Latihan aksara teu acan dipedalkeun. Buka kelas Aksara Sunda kanggo ningali matéri nu parantos sayogi.",
    "Mulai dari materi": "Mimitian tina matéri",
    "Kenali bentuk aksara dan cara membacanya sebelum menjawab soal.": "Wawanohan kana wangun aksara sareng cara macana sateuacan ngajawab patalékan.",
    "Buka kelas Aksara": "Buka kelas Aksara",
    "Gunakan palet aksara pada soal menulis jika papan ketik belum mendukung.": "Anggo palét aksara dina patalékan nyerat upami papan ketik teu acan ngadukung.",
    Selesai: "Réngsé",
    "Sedang dipelajari": "Nuju dipalajari",
    "Cari pelajaran, kosakata, atau aksara": "Téangan pangajaran, kekecapan, atanapi aksara",
    "Masukkan kata kunci untuk mencari materi yang sudah terbit.": "Lebetkeun kecap konci kanggo milarian matéri nu parantos dipedalkeun.",
    "Tandai selesai": "Tandaan réngsé",
    "Tanya materi": "Taroskeun matéri",
    "Tanya Tutor AI": "Taroskeun Tutor AI",
    "Buka Tutor AI penuh": "Buka Tutor AI lengkep",
    "Tutup chat": "Tutup obrolan",
    "Tanya Tutor AI tentang materi ini": "Taroskeun Tutor AI ngeunaan matéri ieu",
    "Ada yang ingin ditanyakan?": "Aya anu badé ditaroskeun?",
    "Tutor akan menjawab dengan konteks materi ini.": "Tutor bakal ngawaler dumasar kana matéri ieu.",
    "Jelaskan bagian ini dengan sederhana": "Jelaskeun bagian ieu ku basa anu gampang",
    "Beri contoh penggunaan materi ini": "Pasihan conto pamakéan matéri ieu",
    ANDA: "ANJEUN",
    "TUTOR AI": "TUTOR AI",
    "Tanyakan tentang materi ini...": "Taroskeun ngeunaan matéri ieu...",
    "Jawaban belum tersedia. Coba lagi.": "Waleran teu acan sayogi. Cobi deui.",
    "Jawaban mengacu pada materi yang sedang dibuka.": "Waleran dumasar kana matéri anu nuju dibuka.",
    "Latihan percakapan": "Latihan paguneman",
    "Pilih bantuan": "Pilih pitulung",
    "Tulis pertanyaan tentang pelajaran yang tersedia...": "Tulis patalékan ngeunaan pangajaran nu sayogi...",
    "Menyiapkan jawaban...": "Nuju nyiapkeun jawaban...",
    "Kirim pesan": "Kirim talatah",
    "Latihan Aksara Sunda": "Latihan Aksara Sunda",
    "Urutan jawaban Anda akan muncul di sini.": "Runtuyan jawaban anjeun bakal muncul di dieu.",
    "Kirim jawaban": "Kirim jawaban",
    "Ketuk karakter pada palet aksara untuk menyusun jawaban, atau ketik langsung.": "Toél karakter dina palét aksara kanggo nyusun jawaban, atanapi ketik langsung.",
    "Baca soal dengan teliti. Jawaban dan penjelasan muncul setelah seluruh soal dikirim.":
        "Baca patalékan kalayan taliti. Jawaban sareng panjelasan muncul saatos sadaya patalékan dikirim.",
    Benar: "Leres",
    "Perlu dipelajari lagi": "Peryogi dipalajari deui",
    "Tidak dijawab": "Teu dijawab",
    AKSARA: "AKSARA",
    BAHASA: "BASA",
    Berjalan: "Nuju lumangsung",
    Mulai: "Mimitian",
    "Latihan & evaluasi": "Latihan & évaluasi",
    "Kumpulan Aksara": "Kumpulan Aksara",
    "Kuis & evaluasi": "Kuis & évaluasi",
    Kuis: "Kuis",
    "Ulasan jawaban": "Tingalian jawaban",
    "Materi tersimpan": "Matéri anu disimpen",
    "TARGET HARIAN": "TARGET SAPOPOÉ",
    "Jaga kebiasaan belajar": "Jaga kabiasaan diajar",
    "aktivitas hari ini": "kagiatan dinten ieu",
    "Pilih target aktivitas per hari": "Pilih target kagiatan sapopoé",
    "AKSES CEPAT": "AKSES GANCANG",
    kelas: "kelas",
    Semua: "Sadaya",
    "Aksara konsonan": "Aksara ngalagena",
    "Tanda bunyi": "Rarangkén",
    "Angka Sunda": "Angka Sunda",
    "Tanda baca": "Tanda baca",
    "Aksara sajarah": "Aksara sajarah",
    "RUANG AKSARA": "ROHANGAN AKSARA",
    "Jelajahi aksara swara, ngalagena, rarangkén, angka, tanda baca, serta bentuk historis.":
        "Jajah aksara swara, ngalagena, rarangkén, angka, tanda baca, sareng wangun sajarah.",
    "Cari nama, bunyi, atau kode Unicode": "Pilarian nami, sora, atanapi kode Unicode",
    "Cari aksara Sunda": "Pilarian Aksara Sunda",
    "Filter kelompok aksara": "Saring kelompok aksara",
    "Pilih karakter untuk menyalinnya": "Pilih karakter kanggo nyalinana",
    "Salin": "Salin",
    "Aksara tidak ditemukan": "Aksara teu kapanggih",
    "Coba kata kunci atau kelompok aksara yang lain.": "Cobi kecap konci atanapi kelompok aksara anu sanés.",
    "Halaman": "Kaca",
    "Lihat semua Aksara Sunda": "Tingali sadaya Aksara Sunda",
    "Latihan & kuis": "Latihan & kuis",
    "Latihan membantu mengulang materi; kuis digunakan untuk evaluasi dan nilai kelulusan.":
        "Latihan ngabantu ngulang matéri; kuis dianggo pikeun évaluasi sareng peunteun kalulusan.",
    "Lihat jawaban": "Tingali jawaban",
    "Ambang kelulusan": "Wates kalulusan",
    "Baca penjelasan dan tinjau kembali soal yang belum tepat.":
        "Baca panjelasan sareng tingali deui soal anu can leres.",
    "Topik yang perlu diperkuat": "Topik anu kedah dikuatkeun",
    "Bagus, kelas ini selesai": "Saé, kelas ieu parantos réngsé",
    "Selesaikan pelajaran ini": "Réngsékeun pangajaran ieu",
    "Ada pelajaran yang terlewat": "Aya pangajaran anu kaliwat",
    Ada: "Aya",
    "jawaban yang belum tepat. Perkuat kembali topik ini:": "jawaban anu can leres. Hayu kuatkeun deui topik ieu:",
    "Baca ulang materi": "Baca deui matéri",
    "Latihan terkait": "Latihan anu patali",
    "Kuis selesai. Tandai pelajaran ini selesai agar progres tersimpan:": "Kuis parantos réngsé. Tandaan pangajaran ieu réngsé supados kamajuan kasimpen:",
    "Tuntaskan pelajaran": "Réngsékeun pangajaran",
    "Pelajaran berikutnya sudah dituntaskan. Materi yang masih belum selesai:": "Pangajaran salajengna parantos réngsé. Matéri anu masih can réngsé:",
    "Semua jawaban tepat. Pelajaran berikutnya yang belum selesai:": "Sadaya jawaban leres. Pangajaran salajengna anu can réngsé:",
    "Lanjutkan ke pelajaran": "Teraskeun kana pangajaran",
    "Semua pelajaran di kelas ini sudah diselesaikan. Pilih kelas lain untuk melanjutkan.": "Sadaya pangajaran dina kelas ieu parantos réngsé. Pilih kelas sanés pikeun neraskeun.",
    "Jelajahi kelas": "Jajah kelas",
    "Kembali ke kelas Aksara": "Balik ka kelas Aksara",
    hari: "dinten",
    "Huruf tambahan": "Aksara tambahan",
    "Dipakai pada ortografi lama": "Dipaké dina éjahan baheula",
    "Tidak dipakai dalam ortografi Sunda modern": "Teu dipaké dina éjahan Sunda kiwari",
    "Nama Unicode historis; pernah salah diidentifikasi": "Ngaran Unicode sajarah; kungsi salah diidentifikasi",
    "Bentuk aksara lama": "Wangun aksara baheula",
    "Untuk ejaan modern, gunakan aksara Ma + Pamaéh": "Pikeun éjahan kiwari, anggo aksara Ma + Pamaéh",
    "Aksara berhasil disalin.": "Aksara parantos disalin.",
    "Aksara tidak dapat disalin. Periksa izin clipboard browser.": "Aksara teu tiasa disalin. Pariksa idin clipboard panyungsi.",
    "Navigasi halaman": "Navigasi kaca",
    "Tampilkan 10 pelajaran lagi": "Tingalikeun deui 10 pangajaran",
    tersisa: "sesana",
    "dijawab": "dijawab",
    "sudah dijawab": "parantos dijawab",
    "belum dijawab": "teu acan dijawab",
    "Nomor soal": "Nomer soal",
    "EVALUASI BELAJAR": "ÉVALUASI DIAJAR",
    "Uji pemahaman materi. Setiap kuis menampilkan aturan waktu, nilai kelulusan, dan sisa percobaan sebelum dimulai.":
        "Uji pamahaman matéri. Unggal kuis nembongkeun wates waktos, peunteun lulus, sareng sésa kasempetan sateuacan dimimitian.",
    "kuis tersedia": "kuis sayogi",
    "kuis ditemukan": "kuis kapanggih",
    "Cari kuis atau materi": "Téangan kuis atanapi matéri",
    "Semua kelas": "Sadaya kelas",
    "Jenis kuis": "Jinis kuis",
    "Semua jenis": "Sadaya jinis",
    "Ada soal menyimak": "Aya soal ngaregepkeun",
    "Status pengerjaan": "Status pagawéan",
    "Pernah dikerjakan": "Kungsi dipigawé",
    "Terapkan": "Terapkeun",
    "Atur ulang": "Atur deui",
    "Tidak ada kuis yang cocok": "Teu aya kuis anu cocog",
    "Ubah atau hapus filter untuk melihat kuis lain.": "Robih atanapi pupus saringan kanggo ningali kuis sanés.",
    "Daftar kuis": "Daptar kuis",
    waktu: "waktos",
    "nilai lulus": "peunteun lulus",
    "Percobaan tersisa": "Kasempetan nyésa",
    "Percobaan tanpa batas": "Kasempetan teu diwatesan",
    "kali dikerjakan": "kali dipigawé",
    "Belum dikerjakan": "Teu acan dipigawé",
    "Mulai kuis": "Mimitian kuis",
    "Lanjutkan kuis": "Teruskeun kuis",
    "Siap memulai kuis?": "Siap ngamimitian kuis?",
    "Periksa aturan kuis sebelum mulai. Waktu mulai dihitung saat kuis dibuka, dan jawaban dikirim setelah Anda mengumpulkan kuis.":
        "Pariksa aturan kuis sateuacan ngamimitian. Waktos mimiti diitung nalika kuis dibuka, sareng jawaban dikirim saatos kuis dikumpulkeun.",
    "Mulai sekarang": "Mimitian ayeuna",
    "Periksa informasi kuis sebelum mulai.": "Pariksa inpormasi kuis sateuacan ngamimitian.",
    "Kuis dimulai. Selamat mengerjakan!": "Kuis dimimitian. Wilujeng ngerjakeun!",
    "Kumpulkan kuis?": "Kumpulkeun kuis?",
    "Masih ada soal belum dijawab": "Masih aya soal anu teu acan dijawab",
    "Pilih minimal satu jawaban sebelum mengumpulkan kuis.": "Pilih sahenteuna hiji jawaban sateuacan ngumpulkeun kuis.",
    "Masih ada": "Masih aya",
    "soal yang belum dijawab. Anda bisa memeriksanya dulu atau tetap mengumpulkan kuis.":
        "soal anu teu acan dijawab. Anjeun tiasa mariksa heula atanapi tetep ngumpulkeun kuis.",
    "Pastikan semua jawaban sudah benar. Setelah dikumpulkan, jawaban tidak dapat diubah.":
        "Pastikeun sadaya jawaban parantos leres. Saatos dikumpulkeun, jawaban teu tiasa dirobih.",
    "Kembali ke kuis": "Balik deui ka kuis",
    "Kumpulkan tetap": "Tetep kumpulkeun",
    "Keluar dari kuis?": "Kaluar tina kuis?",
    "Jawaban kuis ini belum dikumpulkan. Jika Anda pindah halaman sekarang, jawaban yang sudah dipilih akan hilang.":
        "Jawaban kuis ieu teu acan dikumpulkeun. Upami anjeun pindah kaca ayeuna, jawaban anu parantos dipilih bakal leungit.",
    "Tetap di kuis": "Tetep dina kuis",
    "Keluar dari kuis": "Kaluar tina kuis",
    "Jawaban kuis sedang dikirim...": "Jawaban kuis nuju dikirim...",
    "Jawaban kuis berhasil dikumpulkan.": "Jawaban kuis parantos hasil dikumpulkeun.",
    "Jawaban kuis gagal dikirim. Periksa kembali sebelum mencoba lagi.": "Jawaban kuis gagal dikirim. Pariksa deui sateuacan nyobian deui.",
    "Server tidak dapat memproses jawaban kuis. Coba lagi.": "Server teu tiasa ngolah jawaban kuis. Cobi deui.",
    "Koneksi terputus. Jawaban kuis belum terkirim.": "Koneksi pegat. Jawaban kuis teu acan dikirim.",
    "soal belum dijawab. Periksa kembali sebelum mengumpulkan.": "soal teu acan dijawab. Pariksa deui sateuacan ngumpulkeun.",
    "Semua soal sudah dijawab. Periksa sekali lagi sebelum dikumpulkan.": "Sadaya soal parantos dijawab. Pariksa sakali deui sateuacan dikumpulkeun.",
    "Jawaban belum dikumpulkan. Konfirmasi sebelum meninggalkan kuis.": "Jawaban teu acan dikumpulkeun. Pastikeun sateuacan ninggalkeun kuis.",
    "Kuis ditinggalkan. Jawaban belum dikumpulkan.": "Kuis ditinggalkeun. Jawaban teu acan dikumpulkeun.",
    "Percobaan habis": "Kasempetan béak",
    "Belum ada kuis tersedia": "Teu acan aya kuis",
    "Kuis akan muncul setelah admin menerbitkan kuis yang memiliki soal.": "Kuis bakal muncul saatos pangurus medalkeun kuis anu parantos dieusian soal.",
    "Kembali ke Beranda": "Balik ka Tepas",
    "KUIS EVALUASI": "KUIS ÉVALUASI",
    "LATIHAN MANDIRI": "LATIHAN MANDIRI",
    "Bisa diulang · tanpa batas waktu": "Tiasa diulang · tanpa wates waktos",
    "Tanpa batas waktu": "Tanpa wates waktos",
    "Progres kuis": "Kamajuan kuis",
    "SOAL KUIS": "SOAL KUIS",
    "SOAL LATIHAN": "SOAL LATIHAN",
    "Sebelum mengumpulkan": "Sateuacan ngumpulkeun",
    "Periksa kembali jawaban sebelum kuis dikumpulkan.": "Pariksa deui jawaban sateuacan kuis dikumpulkeun.",
    "Batas percobaan kuis tercapai": "Wates kasempetan kuis parantos kahontal",
    "Anda sudah menggunakan semua kesempatan untuk kuis ini.": "Anjeun parantos nganggo sadaya kasempetan pikeun kuis ieu.",
    "Nilai lulus": "Peunteun lulus",
    "Sisa percobaan": "Kasempetan nyésa",
    "soal untuk ditinjau": "soal pikeun ditingali",
    "BELAJAR DARI HASIL": "DIAJAR TINA HASIL",
    "Tinjau jawaban yang keliru dari percobaan terakhir tiap soal, lalu ulangi latihan untuk memperkuat pemahaman.":
        "Tingali jawaban anu lepat tina kasempetan pamungkas unggal soal, teras balikan latihan pikeun nguatkeun pamahaman.",
    "Semua jawaban terbaru sudah benar": "Sadaya jawaban panganyarna parantos leres",
    "Setelah mengerjakan latihan, bagian yang perlu dipelajari ulang akan muncul di sini.": "Sanggeus ngaréngsékeun latihan, bagian anu kedah diulang diajar bakal muncul di dieu.",
    "Buka materi terkait": "Buka matéri patali",
    "PUSTAKA PRIBADI": "PUSTAKA PRIBADI",
    "Kumpulkan kosakata dan contoh yang ingin Anda pelajari lagi.": "Kumpulkeun kekecapan sareng conto anu badé dipalajari deui.",
    "Cari materi tersimpan": "Pilarian matéri anu disimpen",
    "Materi tidak ditemukan": "Matéri teu kapanggih",
    "Belum ada materi tersimpan": "Teu acan aya matéri anu disimpen",
    "Tekan ikon simpan pada blok kosakata atau aksara di dalam pelajaran untuk menyimpannya di sini.": "Toél ikon simpen dina blok kekecapan atanapi aksara dina pangajaran pikeun nyimpenna di dieu.",
    "Coba kata kunci yang berbeda.": "Cobi kecap konci anu sanés.",
    "Jelajahi pelajaran": "Jajah pangajaran",
    "Kumpulan kosakata": "Kumpulan kekecapan",
    "Tampilkan nomor soal": "Tingalikeun nomer soal",
    "LATIHAN & KUIS DIKERJAKAN": "LATIHAN & KUIS DIPIGAWÉ",
    "Coba kuis lagi": "Cobian deui kuis",
    "Tanda rarangkén ditampilkan dengan lingkaran bantu. Saat disalin, hanya tanda aslinya yang disalin.":
        "Tanda rarangkén ditingalikeun nganggo bunderan pangbantu. Nalika disalin, ngan tanda aslina anu disalin.",
    "Ulangan terjadwal": "Ngulang terjadwal",
    "Ulangi kosakata dan aksara agar lebih mudah diingat.": "Balikan kekecapan sareng aksara supados langkung gampang diinget.",
    "INGAT LEBIH LAMA": "INGET LEUWIH LILA",
    "Ulangi kosakata dan aksara yang sudah dipelajari. Beri nilai seberapa mudah Anda mengingatnya agar jadwal berikutnya menyesuaikan.":
        "Balikan kekecapan sareng aksara anu parantos diajar. Pilih sabaraha gampang anjeun ngingetna supados jadwal salajengna tiasa nyaluyukeun.",
    "perlu diulang": "kudu diulang",
    tersimpan: "disimpen",
    "tersisa hari ini": "sésa dinten ieu",
    "Coba ingat artinya": "Cobian émut hartina",
    "Bunyi atau bacaan aksara ini apa?": "Kumaha sora atanapi bacaan aksara ieu?",
    "Tampilkan arti dan jawaban": "Tingalikeun harti sareng jawaban",
    "Jawaban": "Waleran",
    "Seberapa mudah Anda mengingatnya?": "Sabaraha gampang anjeun ngingetna?",
    "Belum ingat": "Teu acan émut",
    Sulit: "Hésé",
    Ingat: "Émut",
    Mudah: "Gampang",
    "Ulangi sebentar lagi": "Balikan deui engké",
    "Jadwalkan lebih cepat": "Jadwalkeun langkung énggal",
    "Lanjutkan jadwal": "Teraskeun jadwal",
    "Jadwalkan lebih lama": "Jadwalkeun langkung lami",
    "Buka materi lengkap": "Buka matéri lengkep",
    "Semua kartu sudah ditinjau": "Sadaya kartu parantos ditilik",
    "Mulai kumpulkan kartu belajar": "Mimitian ngumpulkeun kartu diajar",
    "Buka pelajaran Bahasa Sunda atau Aksara Sunda. Kosakata dan karakter yang Anda pelajari akan masuk ke sini secara otomatis.":
        "Buka matéri Basa Sunda atanapi Aksara Sunda. Kekecapan sareng karakter anu parantos diajar bakal otomatis diasupkeun ka dieu.",
    "Kartu berikutnya dijadwalkan pada": "Kartu salajengna dijadwalkeun dina",
    "Anda bisa kembali saat waktunya tiba.": "Anjeun tiasa uih deui nalika waktosna sumping.",
    "Belum ada kartu yang jatuh tempo. Kartu baru akan muncul setelah Anda membuka pelajaran.":
        "Teu acan aya kartu anu kedah diulang. Kartu anyar bakal muncul saatos anjeun muka pangajaran.",
    "Buka materi belajar": "Buka matéri diajar",
    "Dengarkan sebelum menjawab": "Dangukeun sateuacan ngawaler",
    "Putar audio, lalu pilih kalimat yang paling sesuai.": "Puter audiona, teras pilih kalimah anu pangcocogna.",
    "Dengarkan kalimatnya": "Dangukeun kalimahna",
    "MENYIMAK": "NYIMAK",
    "Menyimak audio": "Nyimak audio",
    "soal menyimak": "soal nyimak",
    "Audio yang didengarkan": "Audio anu didangukeun",
    "Pertanyaan setelah audio": "Patarosan saatos audio",
    "Kalimat Sunda apa yang Anda dengar?": "Kalimah Sunda naon anu kadéngé?",
    "Unggah kalimat Bahasa Sunda yang ingin ditebak pelajar. Maksimum 10 MB.": "Unggah rekaman kalimah Basa Sunda anu badé ditebak ku murid. Maksimum 10 MB.",
    "Rekaman soal": "Rekaman soal",
    "Unggah suara kalimat Bahasa Sunda, maksimum 10 MB. Format: MP3, WAV, OGG, M4A, atau WEBM.": "Unggah sora kalimah Basa Sunda, maksimum 10 MB. Formatna MP3, WAV, OGG, M4A, atanapi WEBM.",
};

export function translateUi(text: string, locale: UiLocale): string {
    return locale === "su" ? (su[text] ?? text) : text;
}

export function t(text: string): string {
    return translateUi(text, typeof document !== "undefined" && document.documentElement.lang === "su" ? "su" : "id");
}

export function useUiLanguage() {
    const { uiLocale } = usePage<{ uiLocale?: UiLocale }>().props;
    const locale: UiLocale = uiLocale === "su" ? "su" : "id";
    return { locale, t: (text: string) => translateUi(text, locale) };
}
